import QuantumFoundations.BornRule.ElementaryRefinement

/-!
# Refinements generated by elementary binary splits

This file isolates the relational part of the split-generation argument.  The
geometric theorem that every finite projective refinement is generated by such
splits is proved separately; here we record transitivity, endpoint refinement,
and propagation of unchanged-cell weights along a generated chain.
-/

namespace QuantumFoundations.BornRule

open scoped Classical InnerProductSpace

noncomputable section

variable {n : ℕ}

/-- Transitivity of the containment-based refinement relation. -/
theorem refines_trans {D₂ D₁ D₀ : Perspective n}
    (h21 : Refines D₂ D₁) (h10 : Refines D₁ D₀) : Refines D₂ D₀ := by
  intro c hc
  obtain ⟨p, hp, hcp⟩ := h21 c hc
  obtain ⟨q, hq, hpq⟩ := h10 p hp
  exact ⟨q, hq, hcp.trans hpq⟩

/-- Reflexivity of refinement. -/
theorem refines_refl (D : Perspective n) : Refines D D := by
  intro c hc
  exact ⟨c, hc, le_refl c⟩

/-- Reflexive-transitive closure of elementary binary splits.  The first
argument is the fine endpoint and the second the coarse endpoint. -/
inductive BinaryGenerated : Perspective n → Perspective n → Prop
  | refl (D : Perspective n) : BinaryGenerated D D
  | step {fine mid coarse : Perspective n} :
      IsBinarySplit fine mid →
      BinaryGenerated mid coarse →
      BinaryGenerated fine coarse

/-- Concatenate two finite chains of binary splits. -/
theorem BinaryGenerated.trans {fine mid coarse : Perspective n}
    (hfm : BinaryGenerated fine mid) (hmc : BinaryGenerated mid coarse) :
    BinaryGenerated fine coarse := by
  induction hfm with
  | refl D => exact hmc
  | @step fine next mid hSplit hRest ih =>
      exact BinaryGenerated.step hSplit ih

/-- Every split-generated chain is, in particular, a refinement. -/
theorem BinaryGenerated.refines {fine coarse : Perspective n}
    (h : BinaryGenerated fine coarse) : Refines fine coarse := by
  induction h with
  | refl D => exact refines_refl D
  | @step fine mid coarse hsplit hgen ih =>
      exact refines_trans hsplit.1 ih

/-- If a nonzero coarse cell is still literally present at the fine endpoint
of a split-generated chain, then it is present at every intermediate endpoint.
This is the small uniqueness fact needed to propagate elementary RC. -/
private theorem shared_cell_present_at_mid
    {fine mid coarse : Perspective n}
    (hSplit : IsBinarySplit fine mid)
    (hGen : BinaryGenerated mid coarse)
    {c : Submodule ℂ (H n)}
    (hcCoarse : c ∈ coarse.cells) (hcFine : c ∈ fine.cells) :
    c ∈ mid.cells := by
  obtain ⟨p, hpMid, hcp⟩ := hSplit.1 c hcFine
  obtain ⟨q, hqCoarse, hpq⟩ := hGen.refines p hpMid
  have hcne : c ≠ ⊥ := coarse.nz c hcCoarse
  have hqeq : q = c :=
    coarse.unique_parent q hqCoarse c hcCoarse hcne
      (hcp.trans hpq) (le_refl c)
  subst q
  have hp_eq : p = c := le_antisymm hpq hcp
  simpa [hp_eq] using hpMid

/-- Elementary split consistency propagates unchanged-cell weights along any
finite split-generated refinement chain. -/
theorem axSplitRC_generated_shared_cell
    (Est : Perspective n → Submodule ℂ (H n) → ℝ)
    (hRC : AxSplitRC Est)
    {fine coarse : Perspective n}
    (hGen : BinaryGenerated fine coarse)
    {c : Submodule ℂ (H n)}
    (hcCoarse : c ∈ coarse.cells) (hcFine : c ∈ fine.cells) :
    Est coarse c = Est fine c := by
  induction hGen with
  | refl D => rfl
  | @step fine mid coarse hSplit hRest ih =>
      have hcMid : c ∈ mid.cells :=
        shared_cell_present_at_mid hSplit hRest hcCoarse hcFine
      calc
        Est coarse c = Est mid c := ih hcCoarse hcMid
        _ = Est fine c := hRC fine mid hSplit c hcMid hcFine

/-- Once the geometric generation theorem is available, elementary RC upgrades
to the finite-refinement stability predicate `AxRC`. -/
theorem axSplitRC_implies_axRC_of_generation
    (Est : Perspective n → Submodule ℂ (H n) → ℝ)
    (hRC : AxSplitRC Est)
    (hGeneration : ∀ D' D : Perspective n, Refines D' D → BinaryGenerated D' D) :
    AxRC Est := by
  intro D' D hRef c hcD hcD'
  exact axSplitRC_generated_shared_cell Est hRC (hGeneration D' D hRef) hcD hcD'

end

end QuantumFoundations.BornRule
