import QuantumFoundations.BornRule.BinarySplitConstruction
import QuantumFoundations.BornRule.RefinementClosure

/-!
# Every finite projective refinement is generated by binary splits

The termination measure is the number of cells of the target fine perspective
that are not yet literally present in the current perspective.  At each step,
a missing target cell is split off from its current parent; the orthogonal
remainder is the supremum of the other target children of that parent.
-/

namespace QuantumFoundations.BornRule

open scoped Classical InnerProductSpace
open Gleason

noncomputable section

variable {n : ℕ}

/-- Every finite refinement of perspectives is a finite chain of elementary
binary splits. -/
theorem refinement_binaryGenerated
    (fine coarse : Perspective n) (hRef : Refines fine coarse) :
    BinaryGenerated fine coarse := by
  classical
  by_cases hMissing : fine.cells \ coarse.cells = ∅
  · have hFineSub : ∀ c ∈ fine.cells, c ∈ coarse.cells := by
      intro c hcFine
      by_contra hcCoarse
      have hc : c ∈ fine.cells \ coarse.cells :=
        Finset.mem_sdiff.mpr ⟨hcFine, hcCoarse⟩
      rw [hMissing] at hc
      simp at hc
    have hCoarseSub : ∀ q ∈ coarse.cells, q ∈ fine.cells := by
      intro q hq
      have hsup := refine_filter_sup_eq fine coarse hRef q hq
      have hchildren : (fine.cells.filter (· ≤ q)).Nonempty := by
        by_contra hne
        have hempty : fine.cells.filter (· ≤ q) = ∅ :=
          Finset.not_nonempty_iff_eq_empty.mp hne
        rw [hempty] at hsup
        simp at hsup
        exact coarse.nz q hq hsup.symm
      obtain ⟨c, hcChild⟩ := hchildren
      obtain ⟨hcFine, hcLe⟩ := Finset.mem_filter.mp hcChild
      have hcCoarse : c ∈ coarse.cells := hFineSub c hcFine
      have hcne : c ≠ ⊥ := fine.nz c hcFine
      have hceq : c = q :=
        coarse.unique_parent hcCoarse hq hcne (le_refl c) hcLe
      simpa [← hceq] using hcFine
    have hcells : fine.cells = coarse.cells := by
      apply Finset.Subset.antisymm
      · intro c hc; exact hFineSub c hc
      · intro c hc; exact hCoarseSub c hc
    have hEq : fine = coarse := Perspective.eq_of_cells hcells
    subst fine
    exact BinaryGenerated.refl coarse
  · have hMissingNE : (fine.cells \ coarse.cells).Nonempty :=
      Finset.nonempty_iff_ne_empty.mpr hMissing
    obtain ⟨a, haMissing⟩ := hMissingNE
    obtain ⟨haFine, haNotCoarse⟩ := Finset.mem_sdiff.mp haMissing
    obtain ⟨q, hqCoarse, haQ⟩ := hRef a haFine
    have hqNotFine : q ∉ fine.cells := by
      intro hqFine
      have haNe : a ≠ ⊥ := fine.nz a haFine
      have haq : a = q :=
        fine.unique_parent haFine hqFine haNe (le_refl a) haQ
      apply haNotCoarse
      simpa [haq] using hqCoarse
    let S : Finset (Submodule ℂ (H n)) := fine.cells.filter (· ≤ q)
    have haS : a ∈ S := by
      exact Finset.mem_filter.mpr ⟨haFine, haQ⟩
    let T : Finset (Submodule ℂ (H n)) := S.erase a
    have hsupS : S.sup id = q := by
      dsimp [S]
      exact refine_filter_sup_eq fine coarse hRef q hqCoarse
    have hTne : T.Nonempty := by
      by_contra hTnone
      have hTempty : T = ∅ := Finset.not_nonempty_iff_eq_empty.mp hTnone
      have hSsingle : S = {a} := by
        ext c
        constructor
        · intro hcS
          by_cases hca : c = a
          · simp [hca]
          · have hcT : c ∈ T := by
              dsimp [T]
              exact Finset.mem_erase.mpr ⟨hca, hcS⟩
            rw [hTempty] at hcT
            simp at hcT
        · intro hc
          have hca : c = a := Finset.mem_singleton.mp hc
          simpa [hca] using haS
      rw [hSsingle] at hsupS
      simp at hsupS
      apply haNotCoarse
      simpa [hsupS] using hqCoarse
    let r : Submodule ℂ (H n) := T.sup id
    have hrNe : r ≠ ⊥ := by
      obtain ⟨b, hbT⟩ := hTne
      have hbS : b ∈ S := Finset.mem_of_mem_erase hbT
      have hbFine : b ∈ fine.cells := (Finset.mem_filter.mp hbS).1
      have hbNe : b ≠ ⊥ := fine.nz b hbFine
      have hbR : b ≤ r := by
        dsimp [r]
        exact Finset.le_sup (f := id) hbT
      intro hrBot
      apply hbNe
      rw [Submodule.eq_bot_iff]
      intro x hx
      have hxbot : x ∈ (⊥ : Submodule ℂ (H n)) := by
        rw [← hrBot]
        exact hbR hx
      exact hxbot
    have haNe : a ≠ ⊥ := fine.nz a haFine
    have hr_le_aperp : r ≤ aᗮ := by
      dsimp [r]
      apply Finset.sup_le
      intro b hbT
      have hbS : b ∈ S := Finset.mem_of_mem_erase hbT
      obtain ⟨hbFine, hbQ⟩ := Finset.mem_filter.mp hbS
      have hba : b ≠ a := (Finset.mem_erase.mp hbT).1
      exact fine.ortho b hbFine a haFine hba
    have har : a ≤ rᗮ :=
      (Submodule.le_orthogonal_orthogonal a).trans
        (Submodule.orthogonal_le hr_le_aperp)
    have hsupAR : a ⊔ r = q := by
      have hInsert : insert a T = S := by
        dsimp [T]
        exact Finset.insert_erase haS
      rw [← hInsert] at hsupS
      simpa [r] using hsupS
    let mid := Perspective.splitCell coarse q a r hqCoarse haNe hrNe har hsupAR
    have hSplit : IsBinarySplit mid coarse :=
      Perspective.splitCell_isBinarySplit coarse q a r hqCoarse haNe hrNe har hsupAR
    have hFineMid : Refines fine mid := by
      intro c hcFine
      obtain ⟨p, hpCoarse, hcP⟩ := hRef c hcFine
      by_cases hpq : p = q
      · subst p
        have hcS : c ∈ S := Finset.mem_filter.mpr ⟨hcFine, hcP⟩
        by_cases hca : c = a
        · subst c
          refine ⟨a, ?_, le_refl a⟩
          change a ∈ coarse.cells.erase q ∪ {a, r}
          exact Finset.mem_union_right _ (Finset.mem_insert_self _ _)
        · have hcT : c ∈ T := by
            dsimp [T]
            exact Finset.mem_erase.mpr ⟨hca, hcS⟩
          have hcR : c ≤ r := by
            dsimp [r]
            exact Finset.le_sup (f := id) hcT
          refine ⟨r, ?_, hcR⟩
          change r ∈ coarse.cells.erase q ∪ {a, r}
          exact Finset.mem_union_right _
            (Finset.mem_insert_of_mem (Finset.mem_singleton_self _))
      · refine ⟨p, ?_, hcP⟩
        change p ∈ coarse.cells.erase q ∪ {a, r}
        exact Finset.mem_union_left _ (Finset.mem_erase.mpr ⟨hpq, hpCoarse⟩)
    have haMid : a ∈ mid.cells := by
      change a ∈ coarse.cells.erase q ∪ {a, r}
      exact Finset.mem_union_right _ (Finset.mem_insert_self _ _)
    have hNewSubset :
        fine.cells \ mid.cells ⊆ (fine.cells \ coarse.cells).erase a := by
      intro c hcNew
      obtain ⟨hcFine, hcNotMid⟩ := Finset.mem_sdiff.mp hcNew
      have hca : c ≠ a := by
        intro hca
        subst c
        exact hcNotMid haMid
      have hcNotCoarse : c ∉ coarse.cells := by
        intro hcCoarse
        have hcq : c ≠ q := by
          intro hcq
          subst c
          exact hqNotFine hcFine
        apply hcNotMid
        change c ∈ coarse.cells.erase q ∪ {a, r}
        exact Finset.mem_union_left _ (Finset.mem_erase.mpr ⟨hcq, hcCoarse⟩)
      exact Finset.mem_erase.mpr
        ⟨hca, Finset.mem_sdiff.mpr ⟨hcFine, hcNotCoarse⟩⟩
    have hMeasure :
        (fine.cells \ mid.cells).card < (fine.cells \ coarse.cells).card := by
      exact (Finset.card_le_card hNewSubset).trans_lt
        (Finset.card_erase_lt_of_mem haMissing)
    have hRec : BinaryGenerated fine mid :=
      refinement_binaryGenerated fine mid hFineMid
    have hFirst : BinaryGenerated mid coarse :=
      BinaryGenerated.step hSplit (BinaryGenerated.refl coarse)
    exact hRec.trans hFirst
termination_by (fine.cells \ coarse.cells).card

/-- Elementary split consistency therefore upgrades to finite refinement
consistency on this perspective domain. -/
theorem axSplitRC_implies_axRC
    (Est : Perspective n → Submodule ℂ (H n) → ℝ)
    (hRC : AxSplitRC Est) : AxRC Est :=
  axSplitRC_implies_axRC_of_generation Est hRC refinement_binaryGenerated

/-- Elementary refinement consistency plus normalization yields Grain
additivity for every finite refinement. -/
theorem axSplitRC_norm_implies_axGrain
    (Est : Perspective n → Submodule ℂ (H n) → ℝ)
    (hRC : AxSplitRC Est) (hNorm : AxNorm Est) : AxGrain Est :=
  axRC_norm_implies_axGrain Est (axSplitRC_implies_axRC Est hRC) hNorm

end

end QuantumFoundations.BornRule
