import QuantumFoundations.Naimark.BinaryImpl.Minimal

/-!
**FR.** # Identités de Gram et isométrie canonique des espaces engendrés

Les deux jambes `eventLeg`/`complementLeg` satisfont des identités de Gram
exactes : `adjoint (eventLeg I) ∘ eventLeg I = E`, `adjoint (complementLeg
I) ∘ complementLeg I = 1 - E`, et le produit croisé s'annule. Ce sont ces
identités qui rendent `E` indépendant de l'implémentation choisie.

Le lemme général `exists_range_isometryEquiv_of_adjoint_comp_self_eq` dit :
si deux applications `f : H →ₗ K` et `g : H →ₗ L` ont le MÊME Gram
(`adjoint f ∘ f = adjoint g ∘ g`), alors leurs images sont canoniquement
isométriques via `f x ↦ g x`. Spécialisé aux deux jambes de deux
implémentations d'un même effet `E`, il donne `eventGeneratedEquiv` et
`complementGeneratedEquiv` : les sous-espaces engendrés par
n'importe quelle implémentation de `E` sont TOUS isométriques entre eux,
canoniquement, quelle que soit la dimension ambiante choisie.

**EN.** # Gram identities and canonical isometry of generated subspaces

The two legs `eventLeg`/`complementLeg` satisfy exact Gram identities:
`adjoint (eventLeg I) ∘ eventLeg I = E`, `adjoint (complementLeg I) ∘
complementLeg I = 1 - E`, and the cross product vanishes. These are the
identities that make `E` independent of the chosen implementation.

The general lemma `exists_range_isometryEquiv_of_adjoint_comp_self_eq`
says: if two maps `f : H →ₗ K` and `g : H →ₗ L` have the SAME Gram matrix
(`adjoint f ∘ f = adjoint g ∘ g`), then their images are canonically
isometric via `f x ↦ g x`. Specialized to the two legs of two
implementations of the same effect `E`, it gives `eventGeneratedEquiv` and
`complementGeneratedEquiv`: the subspaces generated by ANY implementation
of `E` are ALL isometric to each other, canonically, regardless of the
chosen ambient dimension.
-/

namespace QuantumFoundations.Naimark.BinaryImpl

open QuantumFoundations Gleason
open scoped InnerProductSpace

noncomputable section

variable {n : ℕ} {E : H n →ₗ[ℂ] H n} {ι : Type} [Fintype ι] [DecidableEq ι]

theorem eventLeg_adjoint_comp_self (I : BinaryImpl n E ι) :
    LinearMap.adjoint (eventLeg I) ∘ₗ eventLeg I = E := by
  apply LinearMap.ext
  intro x
  show LinearMap.adjoint (eventLeg I) (eventLeg I x) = E x
  have hadj : LinearMap.adjoint (eventLeg I) = LinearMap.adjoint I.encoding ∘ₗ I.cell := by
    show LinearMap.adjoint (I.cell ∘ₗ I.encoding) = LinearMap.adjoint I.encoding ∘ₗ I.cell
    rw [LinearMap.adjoint_comp, I.cell_symmetric.adjoint_eq]
  rw [hadj]
  show LinearMap.adjoint I.encoding (I.cell (eventLeg I x)) = E x
  have hidem : I.cell (eventLeg I x) = eventLeg I x := by
    show I.cell (I.cell (I.encoding x)) = I.cell (I.encoding x)
    have h := LinearMap.congr_fun I.cell_idempotent (I.encoding x)
    simpa using h
  rw [hidem]
  show LinearMap.adjoint I.encoding (I.cell (I.encoding x)) = E x
  have hrealizes := LinearMap.congr_fun I.realizes x
  simpa using hrealizes

theorem complementLeg_adjoint_comp_self (I : BinaryImpl n E ι) :
    LinearMap.adjoint (complementLeg I) ∘ₗ complementLeg I = 1 - E := by
  apply LinearMap.ext
  intro x
  show LinearMap.adjoint (complementLeg I) (complementLeg I x) = (1 - E) x
  have hadj : LinearMap.adjoint (complementLeg I) = LinearMap.adjoint I.encoding ∘ₗ I.complementCell := by
    show LinearMap.adjoint (I.complementCell ∘ₗ I.encoding) = LinearMap.adjoint I.encoding ∘ₗ I.complementCell
    rw [LinearMap.adjoint_comp, I.complementCell_isProjection.isSymmetric.adjoint_eq]
  rw [hadj]
  show LinearMap.adjoint I.encoding (I.complementCell (complementLeg I x)) = (1 - E) x
  have hidem : I.complementCell (complementLeg I x) = complementLeg I x := by
    show I.complementCell (I.complementCell (I.encoding x)) = I.complementCell (I.encoding x)
    have h := LinearMap.congr_fun I.complementCell_isProjection.isIdempotentElem (I.encoding x)
    simpa using h
  rw [hidem]
  show LinearMap.adjoint I.encoding (I.complementCell (I.encoding x)) = (1 - E) x
  have hsplit : I.complementCell (I.encoding x) = I.encoding x - I.cell (I.encoding x) := by
    show (1 - I.cell) (I.encoding x) = I.encoding x - I.cell (I.encoding x)
    simp
  rw [hsplit, map_sub]
  have h1 : LinearMap.adjoint I.encoding (I.encoding x) = x := by
    have h := LinearMap.congr_fun I.encoding_isometry x
    simpa using h
  have h2 : LinearMap.adjoint I.encoding (I.cell (I.encoding x)) = E x := by
    have h := LinearMap.congr_fun I.realizes x
    simpa using h
  rw [h1, h2]
  show x - E x = x - E x
  rfl

theorem event_complement_cross_gram_eq_zero (I : BinaryImpl n E ι) :
    LinearMap.adjoint (eventLeg I) ∘ₗ complementLeg I = 0 := by
  apply LinearMap.ext
  intro x
  show LinearMap.adjoint (eventLeg I) (complementLeg I x) = 0
  have hadj : LinearMap.adjoint (eventLeg I) = LinearMap.adjoint I.encoding ∘ₗ I.cell := by
    show LinearMap.adjoint (I.cell ∘ₗ I.encoding) = LinearMap.adjoint I.encoding ∘ₗ I.cell
    rw [LinearMap.adjoint_comp, I.cell_symmetric.adjoint_eq]
  rw [hadj]
  show LinearMap.adjoint I.encoding (I.cell (complementLeg I x)) = 0
  have hzero : I.cell (complementLeg I x) = 0 := by
    show I.cell (I.complementCell (I.encoding x)) = 0
    have h := LinearMap.congr_fun I.cell_comp_complement_eq_zero (I.encoding x)
    simpa using h
  rw [hzero, map_zero]

/-- If `adjoint f ∘ f = adjoint g ∘ g`, then `f` and `g` have the same
kernel, and there is a canonical linear isometry equivalence between their
ranges sending `f x` to `g x` for every `x`. -/
theorem exists_range_isometryEquiv_of_adjoint_comp_self_eq {H K L : Type*}
    [NormedAddCommGroup H] [NormedAddCommGroup K] [NormedAddCommGroup L]
    [InnerProductSpace ℂ H] [InnerProductSpace ℂ K] [InnerProductSpace ℂ L]
    [FiniteDimensional ℂ H] [FiniteDimensional ℂ K] [FiniteDimensional ℂ L]
    (f : H →ₗ[ℂ] K) (g : H →ₗ[ℂ] L)
    (hfg : LinearMap.adjoint f ∘ₗ f = LinearMap.adjoint g ∘ₗ g) :
    ∃ U : LinearMap.range f ≃ₗᵢ[ℂ] LinearMap.range g,
      (∀ x : H, (U ⟨f x, LinearMap.mem_range_self f x⟩ : L) = g x) ∧
      ∀ y1 y2 : LinearMap.range f, ⟪(U y1 : L), (U y2 : L)⟫_ℂ = ⟪(y1 : K), (y2 : K)⟫_ℂ := by
  have hinner : ∀ x y : H, ⟪f x, f y⟫_ℂ = ⟪g x, g y⟫_ℂ := by
    intro x y
    rw [← LinearMap.adjoint_inner_right f x (f y)]
    have h := LinearMap.congr_fun hfg y
    simp only [LinearMap.comp_apply] at h
    rw [h]
    exact LinearMap.adjoint_inner_right g x (g y)
  have hker : LinearMap.ker f = LinearMap.ker g := by
    apply Submodule.ext
    intro x
    rw [LinearMap.mem_ker, LinearMap.mem_ker, ← inner_self_eq_zero (𝕜 := ℂ) (x := f x),
      ← inner_self_eq_zero (𝕜 := ℂ) (x := g x), hinner x x]
  set Φ : LinearMap.range f ≃ₗ[ℂ] LinearMap.range g :=
    (f.quotKerEquivRange.symm).trans ((Submodule.quotEquivOfEq _ _ hker).trans g.quotKerEquivRange)
    with hΦ_def
  have hΦ_apply : ∀ x : H, (Φ ⟨f x, LinearMap.mem_range_self f x⟩ : L) = g x := by
    intro x
    show (((Submodule.quotEquivOfEq (LinearMap.ker f) (LinearMap.ker g) hker).trans
      g.quotKerEquivRange) (f.quotKerEquivRange.symm ⟨f x, LinearMap.mem_range_self f x⟩) : L) = g x
    have h1 : f.quotKerEquivRange.symm (⟨f x, LinearMap.mem_range_self f x⟩ : LinearMap.range f)
        = Submodule.Quotient.mk x := by
      apply f.quotKerEquivRange.injective
      rw [LinearEquiv.apply_symm_apply]
      exact Subtype.ext (LinearMap.quotKerEquivRange_apply_mk f x).symm
    rw [LinearEquiv.trans_apply, h1]
    show (g.quotKerEquivRange (Submodule.quotEquivOfEq (LinearMap.ker f) (LinearMap.ker g) hker
      (Submodule.Quotient.mk x)) : L) = g x
    rw [show Submodule.quotEquivOfEq (LinearMap.ker f) (LinearMap.ker g) hker
        (Submodule.Quotient.mk x) = Submodule.Quotient.mk x from rfl]
    exact LinearMap.quotKerEquivRange_apply_mk g x
  have hΦinner : ∀ y1 y2 : LinearMap.range f, ⟪(Φ y1 : L), (Φ y2 : L)⟫_ℂ = ⟪(y1 : K), (y2 : K)⟫_ℂ := by
    intro y1 y2
    obtain ⟨x1, hx1⟩ := y1.2
    obtain ⟨x2, hx2⟩ := y2.2
    have hy1 : y1 = ⟨f x1, LinearMap.mem_range_self f x1⟩ := Subtype.ext hx1.symm
    have hy2 : y2 = ⟨f x2, LinearMap.mem_range_self f x2⟩ := Subtype.ext hx2.symm
    rw [hy1, hy2]
    show ⟪(Φ ⟨f x1, LinearMap.mem_range_self f x1⟩ : L), (Φ ⟨f x2, LinearMap.mem_range_self f x2⟩ : L)⟫_ℂ
      = ⟪(⟨f x1, LinearMap.mem_range_self f x1⟩ : LinearMap.range f),
        (⟨f x2, LinearMap.mem_range_self f x2⟩ : LinearMap.range f)⟫_ℂ
    rw [hΦ_apply x1, hΦ_apply x2]
    show ⟪g x1, g x2⟫_ℂ = ⟪f x1, f x2⟫_ℂ
    exact (hinner x1 x2).symm
  exact ⟨LinearEquiv.isometryOfInner Φ hΦinner, hΦ_apply, hΦinner⟩

/-- Ambient-to-ambient variant of
`exists_range_isometryEquiv_of_adjoint_comp_self_eq`: if `f` and `g` are
additionally SURJECTIVE, the resulting isometry equivalence identifies the
whole codomains `K` and `L` directly, with no range-subtype involved. Used
by `MinimalUniqueness.lean` for `minimal_strictIso`, where working with
`LinearMap.range` subtypes of `EuclideanSpace` triggers a persistent
`Module`-instance mismatch in `LinearIsometryEquiv.inner_map_map`/
`LinearEquiv.isometryOfInner` (a genuine Mathlib diamond between
`EuclideanSpace`'s own instance path and the generic one expected by these
lemmas at an explicit `Submodule` type) that this ambient-space route
avoids entirely. -/
theorem exists_isometryEquiv_of_adjoint_comp_self_eq_of_surjective {H K L : Type*}
    [NormedAddCommGroup H] [NormedAddCommGroup K] [NormedAddCommGroup L]
    [InnerProductSpace ℂ H] [InnerProductSpace ℂ K] [InnerProductSpace ℂ L]
    [FiniteDimensional ℂ H] [FiniteDimensional ℂ K] [FiniteDimensional ℂ L]
    (f : H →ₗ[ℂ] K) (g : H →ₗ[ℂ] L)
    (hfg : LinearMap.adjoint f ∘ₗ f = LinearMap.adjoint g ∘ₗ g)
    (hf : Function.Surjective f) (hg : Function.Surjective g) :
    ∃ U : K ≃ₗᵢ[ℂ] L, ∀ x : H, U (f x) = g x := by
  have hinner : ∀ x y : H, ⟪f x, f y⟫_ℂ = ⟪g x, g y⟫_ℂ := by
    intro x y
    rw [← LinearMap.adjoint_inner_right f x (f y)]
    have h := LinearMap.congr_fun hfg y
    simp only [LinearMap.comp_apply] at h
    rw [h]
    exact LinearMap.adjoint_inner_right g x (g y)
  have hker : LinearMap.ker f = LinearMap.ker g := by
    apply Submodule.ext
    intro x
    rw [LinearMap.mem_ker, LinearMap.mem_ker, ← inner_self_eq_zero (𝕜 := ℂ) (x := f x),
      ← inner_self_eq_zero (𝕜 := ℂ) (x := g x), hinner x x]
  set Φ : K ≃ₗ[ℂ] L :=
    (LinearMap.quotKerEquivOfSurjective f hf).symm.trans
      ((Submodule.quotEquivOfEq _ _ hker).trans (LinearMap.quotKerEquivOfSurjective g hg))
    with hΦ_def
  have hΦ_apply : ∀ x : H, Φ (f x) = g x := by
    intro x
    show (((Submodule.quotEquivOfEq (LinearMap.ker f) (LinearMap.ker g) hker).trans
      (LinearMap.quotKerEquivOfSurjective g hg)) ((LinearMap.quotKerEquivOfSurjective f hf).symm (f x))) = g x
    have h1 : (LinearMap.quotKerEquivOfSurjective f hf).symm (f x) = Submodule.Quotient.mk x := by
      apply (LinearMap.quotKerEquivOfSurjective f hf).injective
      rw [LinearEquiv.apply_symm_apply]
      exact (LinearMap.quotKerEquivOfSurjective_apply_mk f hf x).symm
    rw [LinearEquiv.trans_apply, h1]
    show (LinearMap.quotKerEquivOfSurjective g hg) (Submodule.quotEquivOfEq (LinearMap.ker f) (LinearMap.ker g) hker
      (Submodule.Quotient.mk x)) = g x
    rw [show Submodule.quotEquivOfEq (LinearMap.ker f) (LinearMap.ker g) hker
        (Submodule.Quotient.mk x) = Submodule.Quotient.mk x from rfl]
    exact LinearMap.quotKerEquivOfSurjective_apply_mk g hg x
  have hΦinner : ∀ y1 y2 : K, ⟪Φ y1, Φ y2⟫_ℂ = ⟪y1, y2⟫_ℂ := by
    intro y1 y2
    obtain ⟨x1, hx1⟩ := hf y1
    obtain ⟨x2, hx2⟩ := hf y2
    rw [← hx1, ← hx2, hΦ_apply, hΦ_apply]
    exact (hinner x1 x2).symm
  exact ⟨LinearEquiv.isometryOfInner Φ hΦinner, hΦ_apply⟩

/-- Specialization to two implementations of the same effect: their
event-generated subspaces are canonically isometric. -/
noncomputable def eventGeneratedEquiv {κ : Type} [Fintype κ] [DecidableEq κ]
    (I : BinaryImpl n E ι) (J : BinaryImpl n E κ) :
    eventGenerated I ≃ₗᵢ[ℂ] eventGenerated J :=
  (exists_range_isometryEquiv_of_adjoint_comp_self_eq (eventLeg I) (eventLeg J)
    (by rw [eventLeg_adjoint_comp_self, eventLeg_adjoint_comp_self])).choose

theorem eventGeneratedEquiv_apply {κ : Type} [Fintype κ] [DecidableEq κ]
    (I : BinaryImpl n E ι) (J : BinaryImpl n E κ) (x : H n) :
    (eventGeneratedEquiv I J ⟨eventLeg I x, LinearMap.mem_range_self _ x⟩ : EuclideanSpace ℂ κ)
      = eventLeg J x :=
  (exists_range_isometryEquiv_of_adjoint_comp_self_eq (eventLeg I) (eventLeg J)
    (by rw [eventLeg_adjoint_comp_self, eventLeg_adjoint_comp_self])).choose_spec.1 x

theorem eventGeneratedEquiv_inner {κ : Type} [Fintype κ] [DecidableEq κ]
    (I : BinaryImpl n E ι) (J : BinaryImpl n E κ) (y1 y2 : eventGenerated I) :
    ⟪(eventGeneratedEquiv I J y1 : EuclideanSpace ℂ κ), (eventGeneratedEquiv I J y2 : EuclideanSpace ℂ κ)⟫_ℂ
      = ⟪(y1 : EuclideanSpace ℂ ι), (y2 : EuclideanSpace ℂ ι)⟫_ℂ :=
  (exists_range_isometryEquiv_of_adjoint_comp_self_eq (eventLeg I) (eventLeg J)
    (by rw [eventLeg_adjoint_comp_self, eventLeg_adjoint_comp_self])).choose_spec.2 y1 y2

/-- Specialization to two implementations of the same effect: their
complement-generated subspaces are canonically isometric. -/
noncomputable def complementGeneratedEquiv {κ : Type} [Fintype κ] [DecidableEq κ]
    (I : BinaryImpl n E ι) (J : BinaryImpl n E κ) :
    complementGenerated I ≃ₗᵢ[ℂ] complementGenerated J :=
  (exists_range_isometryEquiv_of_adjoint_comp_self_eq (complementLeg I) (complementLeg J)
    (by rw [complementLeg_adjoint_comp_self, complementLeg_adjoint_comp_self])).choose

theorem complementGeneratedEquiv_apply {κ : Type} [Fintype κ] [DecidableEq κ]
    (I : BinaryImpl n E ι) (J : BinaryImpl n E κ) (x : H n) :
    (complementGeneratedEquiv I J ⟨complementLeg I x, LinearMap.mem_range_self _ x⟩
      : EuclideanSpace ℂ κ) = complementLeg J x :=
  (exists_range_isometryEquiv_of_adjoint_comp_self_eq (complementLeg I) (complementLeg J)
    (by rw [complementLeg_adjoint_comp_self, complementLeg_adjoint_comp_self])).choose_spec.1 x

theorem complementGeneratedEquiv_inner {κ : Type} [Fintype κ] [DecidableEq κ]
    (I : BinaryImpl n E ι) (J : BinaryImpl n E κ) (y1 y2 : complementGenerated I) :
    ⟪(complementGeneratedEquiv I J y1 : EuclideanSpace ℂ κ),
      (complementGeneratedEquiv I J y2 : EuclideanSpace ℂ κ)⟫_ℂ
      = ⟪(y1 : EuclideanSpace ℂ ι), (y2 : EuclideanSpace ℂ ι)⟫_ℂ :=
  (exists_range_isometryEquiv_of_adjoint_comp_self_eq (complementLeg I) (complementLeg J)
    (by rw [complementLeg_adjoint_comp_self, complementLeg_adjoint_comp_self])).choose_spec.2 y1 y2

end

end QuantumFoundations.Naimark.BinaryImpl
