import QuantumFoundations.Naimark.BinaryImpl.Nontriviality
import QuantumFoundations.Naimark.BinaryImpl.StrictClassification

/-!
**FR.** # Module C (Porte Ω) — synthèse : classification stricte des implémentations de Naimark

Ce module formalise la structure EXACTE des implémentations binaires
concrètes d'un effet fixé `E : H n →ₗ[ℂ] H n`, au-dessus du théorème de
Naimark déjà établi (`Naimark/Main.lean`), sans jamais le redémontrer.

**Ce qui est ÉTABLI (tous les fichiers listés compilent, sans preuve
incomplète, sans axiome, sans décision native forcée) :**

1. `BinaryImpl n E ι`/`StrictIso` (`Defs.lean`) : une implémentation est un
   encodage isométrique plus une cellule de mesure dont le tiré-en-arrière
   redonne `E` ; `StrictIso` est STRICTEMENT plus fort que la seule
   égalité des effets induits.
2. `canonicalBinaryImpl`/`canonicalSelectedOutcomeImpl` (`Canonical.lean`) :
   les implémentations canoniques via `naimark_dilation`, jamais
   reprouvées.
3. `minimalSubspace`/`IsMinimal` (`Minimal.lean`) et les identités de Gram
   `eventGeneratedEquiv`/`complementGeneratedEquiv` (`GramRange.lean`) :
   les sous-espaces engendrés par N'IMPORTE QUELLE implémentation de `E`
   sont canoniquement isométriques entre eux.
4. **`minimal_strictIso`** (`MinimalUniqueness.lean`) : deux implémentations
   MINIMALES d'un même effet sont TOUJOURS strictement isomorphes —
   théorème central du module.
5. La classification stricte complète `strictIso_iff_residualDims_eq`
   (`StrictClassification.lean`) identifie exactement les deux dimensions
   résiduelles `excessEventDim` et `excessComplementDim` comme invariants
   de `StrictIso`. Les coordonnées binaires, l'espace Ω commun,
   `omegaAssembly`, son entrelacement et son Gram sont établis dans
   `SumCoordinates.lean`, `OrthogonalCoordinates.lean` et
   `OmegaAssembly.lean`.
6. `replicatedAncillaImpl`/`rankRatio`/`rankRatio_replicatedAncilla`
   (`ReplicatedAncilla.lean`) : ajouter une ancilla répliquée ne change
   JAMAIS le ratio de rang.
7. Le contre-exemple canonique binaire/ternaire (`TernaryFusion.lean`,
   ratios `1/2` vs `1/3`) : sa non-isomorphie stricte SURVIT à toute
   réplication d'ancilla arbitraire des deux côtés.
8. `ImplValuation`/`StrictIsoInvariant`/`ReplicatedAncillaNeutral`
   (`Valuation.lean`) : `rankRatio` satisfait les deux ; `ambientDim`
   sépare les deux notions (satisfait la première, pas la seconde).
9. `Nonvacuity.lean`/`Nontriviality.lean` : les structures ci-dessus sont
   satisfiables ET non-triviales (témoins concrets).

**Phases suivantes :**

Les extensions résiduelles et les valuations qui en dépendent restent des
jalons distincts ; elles ne sont pas nécessaires à la classification stricte.

**EN.** # Module C (Omega Gate) — synthesis: strict classification of Naimark implementations

This module formalizes the EXACT structure of concrete binary
implementations of a fixed effect `E : H n →ₗ[ℂ] H n`, on top of the
already-established Naimark theorem (`Naimark/Main.lean`), without ever
re-proving it.

**What IS established (every file listed compiles, with no incomplete
proof, no axiom, no forced native decision):**

1. `BinaryImpl n E ι`/`StrictIso` (`Defs.lean`): an implementation is an
   isometric encoding plus a measurement cell whose pullback recovers
   `E`; `StrictIso` is STRICTLY stronger than mere equality of the
   induced effects.
2. `canonicalBinaryImpl`/`canonicalSelectedOutcomeImpl` (`Canonical.lean`):
   the canonical implementations via `naimark_dilation`, never re-proved.
3. `minimalSubspace`/`IsMinimal` (`Minimal.lean`) and the Gram identities
   `eventGeneratedEquiv`/`complementGeneratedEquiv` (`GramRange.lean`):
   the subspaces generated by ANY implementation of `E` are canonically
   isometric to one another.
4. **`minimal_strictIso`** (`MinimalUniqueness.lean`): two MINIMAL
   implementations of the same effect are ALWAYS strictly isomorphic —
   the module's central theorem.
5. The complete strict classification
   `strictIso_iff_residualDims_eq` (`StrictClassification.lean`) identifies
   exactly the two residual dimensions `excessEventDim` and
   `excessComplementDim` as the invariants of `StrictIso`. The binary
   coordinates, common Ω-space, `omegaAssembly`, cell intertwining and Gram
   identity are established in `SumCoordinates.lean`,
   `OrthogonalCoordinates.lean` and `OmegaAssembly.lean`.
6. `replicatedAncillaImpl`/`rankRatio`/`rankRatio_replicatedAncilla`
   (`ReplicatedAncilla.lean`): adding a replicated ancilla NEVER changes
   the rank ratio.
7. The canonical binary/ternary counterexample (`TernaryFusion.lean`,
   ratios `1/2` vs `1/3`): its strict non-isomorphism SURVIVES arbitrary
   ancilla replication on both sides.
8. `ImplValuation`/`StrictIsoInvariant`/`ReplicatedAncillaNeutral`
   (`Valuation.lean`): `rankRatio` satisfies both; `ambientDim` separates
   the two notions (satisfies the first, not the second).
9. `Nonvacuity.lean`/`Nontriviality.lean`: the structures above are
   satisfiable AND nontrivial (concrete witnesses).

**Next phases:**

Residual extensions and the valuations depending on them remain separate
milestones; they are not needed for the strict classification.

- `ResidualExtension.lean`/`minimalCore` (direct-sum extension of a
  minimal core by residual sectors, and the decomposition of ANY
  implementation into this form) are NOT built: their intended use
  depends directly on the point above.
- `ResidualExtensionNeutral`/`MinimalImplValuation`/the "residually
  neutral valuations ≃ minimal valuations" equivalence/
  `implementationIndependent_of_residualNeutral` (`Valuation.lean`) are
  NOT formalized, for the same reason.
- The nonvacuity of `IsMinimal` (a CONCRETE minimal-implementation
  witness) is not established (`Nonvacuity.lean`): it would require an
  identity between the kernel of `eventLeg`/`complementLeg` and that of
  `E`/`1-E`, not yet formalized.

A block on a late phase does not license documenting the corresponding
theorem as finished: these gaps are therefore explicitly flagged here, in
the synthesis file, rather than hidden.
-/

namespace QuantumFoundations.Naimark.BinaryImpl

open QuantumFoundations Gleason
open scoped InnerProductSpace

noncomputable section

variable {n : ℕ} {E : H n →ₗ[ℂ] H n}

/-- Capstone: combining `minimal_strictIso` (`MinimalUniqueness.lean`)
with `StrictIso.rankRatio_eq` (`ReplicatedAncilla.lean`) -- `rankRatio` is
already a COMPLETE invariant on minimal implementations: any two minimal
implementations of the same effect agree on it, with the complete strict classification `strictIso_iff_residualDims_eq`. -/
theorem rankRatio_eq_of_isMinimal {ι κ : Type} [Fintype ι] [DecidableEq ι] [Fintype κ]
    [DecidableEq κ] {I : BinaryImpl n E ι} {J : BinaryImpl n E κ} (hI : IsMinimal I)
    (hJ : IsMinimal J) : rankRatio I = rankRatio J :=
  StrictIso.rankRatio_eq (minimal_strictIso hI hJ)

end

end QuantumFoundations.Naimark.BinaryImpl




