import QuantumFoundations.Naimark.BinaryImpl.Canonical

/-!
**FR.** # Sous-espace généré minimal d'une implémentation binaire

Pour une implémentation `I : BinaryImpl n E ι`, les deux "jambes"
`eventLeg I := I.cell ∘ I.encoding` et `complementLeg I := I.complementCell
∘ I.encoding` engendrent deux sous-espaces ORTHOGONAUX de l'espace
ambiant (`eventGenerated`/`complementGenerated`), dont la somme
`minimalSubspace I` est stable sous `I.cell` ET sous son orthogonal
(`minimalSubspace_isReducing`) : c'est la partie de l'espace ambiant
réellement "utilisée" par l'implémentation. `IsMinimal I` dit que cette
partie est TOUT l'espace ambiant — aucune dimension résiduelle inutile.

**EN.** # Minimal generated subspace of a binary implementation

For an implementation `I : BinaryImpl n E ι`, the two "legs" `eventLeg I
:= I.cell ∘ I.encoding` and `complementLeg I := I.complementCell ∘
I.encoding` generate two ORTHOGONAL subspaces of the ambient space
(`eventGenerated`/`complementGenerated`), whose sum `minimalSubspace I` is
stable under `I.cell` AND under its orthogonal complement
(`minimalSubspace_isReducing`): this is the part of the ambient space
actually "used" by the implementation. `IsMinimal I` says this part is the
WHOLE ambient space — no wasted residual dimension.
-/

namespace QuantumFoundations.Naimark.BinaryImpl

open QuantumFoundations Gleason
open scoped InnerProductSpace

noncomputable section

variable {n : ℕ} {E : H n →ₗ[ℂ] H n} {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The "event leg": the encoding followed by the measurement cell. -/
noncomputable def eventLeg (I : BinaryImpl n E ι) : H n →ₗ[ℂ] EuclideanSpace ℂ ι :=
  I.cell ∘ₗ I.encoding

/-- The "complement leg": the encoding followed by the complementary cell. -/
noncomputable def complementLeg (I : BinaryImpl n E ι) : H n →ₗ[ℂ] EuclideanSpace ℂ ι :=
  I.complementCell ∘ₗ I.encoding

/-- The subspace of the ambient space generated by the event leg. -/
def eventGenerated (I : BinaryImpl n E ι) : Submodule ℂ (EuclideanSpace ℂ ι) :=
  LinearMap.range (eventLeg I)

/-- The subspace of the ambient space generated by the complement leg. -/
def complementGenerated (I : BinaryImpl n E ι) : Submodule ℂ (EuclideanSpace ℂ ι) :=
  LinearMap.range (complementLeg I)

/-- The minimal subspace of the ambient space actually used by `I`: the
span of both legs. -/
def minimalSubspace (I : BinaryImpl n E ι) : Submodule ℂ (EuclideanSpace ℂ ι) :=
  eventGenerated I ⊔ complementGenerated I

theorem eventGenerated_le_cellRange (I : BinaryImpl n E ι) :
    eventGenerated I ≤ LinearMap.range I.cell := by
  rintro y ⟨x, rfl⟩
  exact ⟨I.encoding x, rfl⟩

theorem complementGenerated_le_cellKernel (I : BinaryImpl n E ι) :
    complementGenerated I ≤ LinearMap.ker I.cell := by
  rintro y ⟨x, rfl⟩
  show I.cell (I.complementCell (I.encoding x)) = 0
  have h := LinearMap.congr_fun (I.cell_comp_complement_eq_zero) (I.encoding x)
  simpa using h

theorem eventGenerated_orthogonal_complementGenerated (I : BinaryImpl n E ι) :
    eventGenerated I ≤ (complementGenerated I)ᗮ := by
  rintro y1 ⟨x1, rfl⟩
  rw [Submodule.mem_orthogonal]
  rintro y2 ⟨x2, rfl⟩
  show ⟪complementLeg I x2, eventLeg I x1⟫_ℂ = 0
  show ⟪I.complementCell (I.encoding x2), I.cell (I.encoding x1)⟫_ℂ = 0
  rw [← I.cell_symmetric (I.complementCell (I.encoding x2)) (I.encoding x1)]
  have h := LinearMap.congr_fun (I.cell_comp_complement_eq_zero) (I.encoding x2)
  simp only [LinearMap.comp_apply, LinearMap.zero_apply] at h
  rw [h, inner_zero_left]

/-- Every encoded vector decomposes as its event-leg image plus its
complement-leg image, hence lies in `minimalSubspace`. -/
theorem encoding_mem_minimalSubspace (I : BinaryImpl n E ι) (x : H n) :
    I.encoding x ∈ minimalSubspace I := by
  have hdecomp : I.encoding x = eventLeg I x + complementLeg I x := by
    show I.encoding x = I.cell (I.encoding x) + I.complementCell (I.encoding x)
    have h := LinearMap.congr_fun I.cell_add_complement_eq_one (I.encoding x)
    simpa using h.symm
  rw [hdecomp]
  exact Submodule.add_mem _ (Submodule.mem_sup_left ⟨x, rfl⟩) (Submodule.mem_sup_right ⟨x, rfl⟩)

theorem cell_maps_minimalSubspace (I : BinaryImpl n E ι) :
    ∀ y ∈ minimalSubspace I, I.cell y ∈ minimalSubspace I := by
  intro y hy
  rw [minimalSubspace, Submodule.mem_sup] at hy
  obtain ⟨a, ⟨x1, rfl⟩, b, ⟨x2, rfl⟩, rfl⟩ := hy
  rw [map_add]
  have ha : I.cell (eventLeg I x1) = eventLeg I x1 := by
    show I.cell (I.cell (I.encoding x1)) = I.cell (I.encoding x1)
    have h := LinearMap.congr_fun I.cell_idempotent (I.encoding x1)
    simpa using h
  have hb : I.cell (complementLeg I x2) = 0 := by
    show I.cell (I.complementCell (I.encoding x2)) = 0
    have h := LinearMap.congr_fun I.cell_comp_complement_eq_zero (I.encoding x2)
    simpa using h
  rw [ha, hb, add_zero]
  exact Submodule.mem_sup_left ⟨x1, rfl⟩

theorem complement_maps_minimalSubspace (I : BinaryImpl n E ι) :
    ∀ y ∈ minimalSubspace I, I.complementCell y ∈ minimalSubspace I := by
  intro y hy
  have h1 := cell_maps_minimalSubspace I y hy
  have h2 : I.complementCell y = y - I.cell y := by
    show (1 - I.cell) y = y - I.cell y
    simp
  rw [h2]
  exact Submodule.sub_mem _ hy h1

/-- `minimalSubspace` is a REDUCING subspace for `I.cell`: the cell
preserves it, and (by symmetry of the cell) also preserves its orthogonal
complement. -/
theorem minimalSubspace_isReducing (I : BinaryImpl n E ι) :
    ∀ z ∈ (minimalSubspace I)ᗮ, I.cell z ∈ (minimalSubspace I)ᗮ := by
  intro z hz
  rw [Submodule.mem_orthogonal] at hz ⊢
  intro w hw
  rw [← I.cell_symmetric w z]
  exact hz (I.cell w) (cell_maps_minimalSubspace I w hw)

/-- `I` is MINIMAL: its ambient space is entirely accounted for by the two
legs, with no leftover residual dimension. -/
def IsMinimal (I : BinaryImpl n E ι) : Prop :=
  minimalSubspace I = ⊤

theorem isMinimal_iff_span_legs_eq_top (I : BinaryImpl n E ι) :
    IsMinimal I ↔ eventGenerated I ⊔ complementGenerated I = ⊤ := Iff.rfl

theorem isMinimal_iff_orthogonal_eq_bot (I : BinaryImpl n E ι) :
    IsMinimal I ↔ (minimalSubspace I)ᗮ = ⊥ :=
  (Submodule.orthogonal_eq_bot_iff).symm

end

end QuantumFoundations.Naimark.BinaryImpl
