import QuantumFoundations.Complexity.SimulatedEvolution.CircuitPersistence
import QuantumFoundations.Complexity.SimulatedEvolution.ThresholdTransport

/-!
# C13f — Persistence under simulated evolution

`NormPreservingEvolution E` is a bare time-indexed family of norm-preserving
operators, with **no** group law required (`evolve (s+t) = evolve s ∘ evolve
t` is not assumed): this is deliberately the minimal honest interface a
target evolution must satisfy for the C13 threshold-transport argument, not
a claim that it is generated by any particular Hamiltonian. A finite circuit
`C` *simulates* this evolution at time `t` when its transported evaluation
is within operator-norm error `ε` of `U.evolve t`
(`CircuitSimulatesEvolutionAt`).

The main theorem combines, in order: (1) exact-circuit persistence of the
margin certificate (C13e, unchanged margin `μ`); (2) distinguishability
transport from `δ + μ` to `δ` (C13c); (3) non-interference transport from
`δ - μ` to `δ` (C13c); (4) reassembly into the ordinary central-threshold
`HasProxyGapAtLeast`. No minimum-complexity definition is unfolded directly.
-/

namespace QuantumFoundations.Complexity.SimulatedEvolution

open Gleason
open QuantumFoundations.BranchesRiedel
open QuantumFoundations.Complexity
open QuantumFoundations.Complexity.OperatorNorm

noncomputable section

/-! ## C13f.1 — Norm-preserving evolution families -/

/-- A time-indexed family of norm-preserving continuous linear maps. No
group law (`evolve 0 = id`, `evolve (s + t) = evolve s ∘ evolve t`) is
required at this minimal level. -/
structure NormPreservingEvolution (E : Type*)
    [NormedAddCommGroup E] [NormedSpace ℂ E] where
  /-- The operator implementing the evolution at time `t`. -/
  evolve : ℝ → E →L[ℂ] E
  /-- Every `evolve t` preserves norms. -/
  norm_apply : ∀ t x, ‖evolve t x‖ = ‖x‖

namespace NormPreservingEvolution

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]

/-- Every time-slice of a norm-preserving evolution is norm preserving in
the C13a sense. -/
theorem isNormPreserving (U : NormPreservingEvolution E) (t : ℝ) :
    IsNormPreserving (U.evolve t) :=
  U.norm_apply t

end NormPreservingEvolution

/-! ## C13f.2 — Circuit simulation certificates -/

/-- A finite circuit `C` simulates the evolution `U` at time `t` with
operator-norm error `ε`. -/
def CircuitSimulatesEvolutionAt {N d : ℕ}
    (U : NormPreservingEvolution (H (d ^ N)))
    (e : H (d ^ N) ≃ₗᵢ[ℂ] Sites N d)
    (t : ℝ) (C : Circuit N d) (ε : ℝ) : Prop :=
  ApproximatesOperator (U.evolve t) (circuitCLMOnH C e) ε

namespace CircuitSimulatesEvolutionAt

variable {N d : ℕ} {U : NormPreservingEvolution (H (d ^ N))}
  {e : H (d ^ N) ≃ₗᵢ[ℂ] Sites N d} {t : ℝ} {C : Circuit N d} {ε ε' : ℝ}

/-- Increasing the simulation-error budget preserves the certificate. -/
theorem mono_error (h : CircuitSimulatesEvolutionAt U e t C ε) (hε : ε ≤ ε') :
    CircuitSimulatesEvolutionAt U e t C ε' :=
  ApproximatesOperator.mono h hε

/-- An exact match between the evolution and the circuit gives simulation
error exactly zero. -/
theorem exact (heq : U.evolve t = circuitCLMOnH C e) :
    CircuitSimulatesEvolutionAt U e t C 0 := by
  unfold CircuitSimulatesEvolutionAt ApproximatesOperator
  rw [heq, sub_self, norm_zero]

end CircuitSimulatesEvolutionAt

/-- Bounded-cost existential form: some circuit of length at most `L`
simulates `U` at time `t` with error at most `ε`. -/
def HasCircuitSimulationAt {N d : ℕ}
    (U : NormPreservingEvolution (H (d ^ N)))
    (e : H (d ^ N) ≃ₗᵢ[ℂ] Sites N d)
    (t : ℝ) (L : ℕ) (ε : ℝ) : Prop :=
  ∃ C : Circuit N d, Circuit.length C ≤ L ∧ CircuitSimulatesEvolutionAt U e t C ε

/-! ## C13f.3 — The main persistence theorem -/

/-- The central C13 theorem: a margin certificate for the initial states,
transported through an exact circuit `E` that simulates the target
evolution `U` at time `t` with error `ε ≤ μ / 2`, certifies the ordinary
central-threshold proxy gap for the `U`-evolved states. -/
theorem margin_gap_persists_under_simulated_evolution {N d : ℕ}
    (U : NormPreservingEvolution (H (d ^ N)))
    (e : H (d ^ N) ≃ₗᵢ[ℂ] Sites N d)
    (a b : H (d ^ N)) (ha : ‖a‖ = 1) (hb : ‖b‖ = 1)
    (δ μ ε : ℝ) (g : ℕ) (t : ℝ) (E : Circuit N d)
    (hGap : HasProxyGapMarginAtLeast e a b δ μ (4 * Circuit.length E + g))
    (hSim : CircuitSimulatesEvolutionAt U e t E ε)
    (hError : 2 * ε ≤ μ) :
    HasProxyGapAtLeast e (U.evolve t a) (U.evolve t b) δ g := by
  have hPersist := margin_gap_persists_under_circuit e a b δ μ E g hGap
  obtain ⟨B, D, hI, hD, hbudget⟩ := hPersist
  have hUnp : IsNormPreserving (U.evolve t) := U.isNormPreserving t
  have hEnp : IsNormPreserving (circuitCLMOnH E e) := circuitCLMOnH_isNormPreserving E e
  refine ⟨B, D, ?_, ?_, hbudget⟩
  · intro C hC
    exact hI C (interferesAt_target_implies_interferesAt_approximation
      hSim hUnp hEnp e C ha hb hC hError)
  · obtain ⟨Cw, hlen, hCw⟩ := hD
    exact ⟨Cw, hlen, distinguishesAt_transport_of_operator_approx
      hSim hUnp hEnp e Cw ha hb hCw hError⟩

/-- The cost-bounded form: a witness circuit of length at most `L`
simulating `U` at time `t` suffices, using only the length bound in the
budget arithmetic. -/
theorem margin_gap_persists_of_hasCircuitSimulationAt {N d : ℕ}
    (U : NormPreservingEvolution (H (d ^ N)))
    (e : H (d ^ N) ≃ₗᵢ[ℂ] Sites N d)
    (a b : H (d ^ N)) (ha : ‖a‖ = 1) (hb : ‖b‖ = 1)
    (δ μ ε : ℝ) (g L : ℕ) (t : ℝ)
    (hSim : HasCircuitSimulationAt U e t L ε)
    (hGap : HasProxyGapMarginAtLeast e a b δ μ (4 * L + g))
    (hError : 2 * ε ≤ μ) :
    HasProxyGapAtLeast e (U.evolve t a) (U.evolve t b) δ g := by
  obtain ⟨E, hlen, hSimE⟩ := hSim
  have hGap' : HasProxyGapMarginAtLeast e a b δ μ (4 * Circuit.length E + g) :=
    hGap.mono_gap (by omega)
  exact margin_gap_persists_under_simulated_evolution U e a b ha hb δ μ ε g t E hGap' hSimE hError

#print axioms margin_gap_persists_under_simulated_evolution
#print axioms margin_gap_persists_of_hasCircuitSimulationAt

end

end QuantumFoundations.Complexity.SimulatedEvolution
