import QuantumFoundations.BornRule.EffectPerspectives.Qubit

/-!
# QB10 — Nonvacuity of the effect-perspective carrier

**Discipline of this repository:** every new hypothesis structure must be
witnessed by a concrete inhabitant, proved without relying on the very
theorem the structure exists to state. `pureStateEstimationRule` therefore
proves `nonneg`/`normalized`/`grain` directly from `IsEffect` and
`sum_eq_one` — never via `Gleason.busch` or `Gleason.busch_born_rule` — by
the same "expectation value" pattern as the pinned dependency's own
`Gleason.pureEffectMeasure` (a reused *pattern*, not a reused declaration:
the carrier here is `EffectPerspective`, a genuinely different type).
-/

namespace QuantumFoundations.BornRule.EffectPerspectives

open scoped InnerProductSpace

noncomputable section

variable {n : ℕ}

/-! ## QB10.1 — The pure-state estimation rule -/

/-- The estimation rule directly generated by a unit vector `ψ`: the weight
of an effect occurrence is its expectation value in `ψ`. Proved without
`Gleason.busch`. -/
def pureStateEstimationRule (ψ : Gleason.H n) (hψ : ‖ψ‖ = 1) : EstimationRule n where
  weight D i := (⟪(D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) ψ, ψ⟫_ℂ).re
  nonneg D i := (D.effects i).2.1.2 ψ
  normalized D := by
    have hsum : (∑ i : Fin D.outcomes, (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n)) ψ = ψ := by
      rw [D.sum_eq_one]; simp
    rw [LinearMap.sum_apply] at hsum
    show (∑ i : Fin D.outcomes, (⟪(D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) ψ, ψ⟫_ℂ).re) = 1
    rw [← Complex.re_sum, ← sum_inner, hsum]
    simp [inner_self_eq_norm_sq_to_K, hψ]
  grain {fine coarse} r j := by
    have happly : (coarse.effects j : Gleason.H n →ₗ[ℂ] Gleason.H n) ψ
        = ∑ i : Fin fine.outcomes,
            if r.parent i = j then (fine.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) ψ else 0 := by
      rw [r.coarse_eq_fiber_sum j, LinearMap.sum_apply]
      apply Finset.sum_congr rfl
      intro i _
      by_cases h : r.parent i = j <;> simp [h]
    show (⟪(coarse.effects j : Gleason.H n →ₗ[ℂ] Gleason.H n) ψ, ψ⟫_ℂ).re
        = ∑ i : Fin fine.outcomes,
            if r.parent i = j then (⟪(fine.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) ψ, ψ⟫_ℂ).re else 0
    rw [happly, sum_inner, Complex.re_sum]
    apply Finset.sum_congr rfl
    intro i _
    by_cases h : r.parent i = j <;> simp [h]

/-! ## QB10.2 — Its null support is contextual -/

theorem pureStateEstimationRule_nullSupport (ψ : Gleason.H n) (hψ : ‖ψ‖ = 1) :
    ContextualNullSupport (pureStateEstimationRule ψ hψ) ψ := by
  intro D i hzero
  show (⟪(D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) ψ, ψ⟫_ℂ).re = 0
  rw [hzero]
  simp

theorem pureStateEstimationRule_weight (ψ : Gleason.H n) (hψ : ‖ψ‖ = 1)
    (D : EffectPerspective n) (i : Fin D.outcomes) :
    (pureStateEstimationRule ψ hψ).weight D i
      = (⟪(D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) ψ, ψ⟫_ℂ).re := rfl

/-! ## QB10.3 — A concrete qubit witness -/

/-- The computational-basis state `|0⟩` on the qubit. -/
def qubitZeroState : Gleason.H 2 := EuclideanSpace.single 0 1

/-- The computational-basis state `|1⟩` on the qubit, orthogonal to
`qubitZeroState`. -/
def qubitOneState : Gleason.H 2 := EuclideanSpace.single 1 1

theorem qubitZeroState_norm : ‖qubitZeroState‖ = 1 := by
  show ‖EuclideanSpace.single (0 : Fin 2) (1 : ℂ)‖ = 1
  simp

theorem qubitOneState_norm : ‖qubitOneState‖ = 1 := by
  show ‖EuclideanSpace.single (1 : Fin 2) (1 : ℂ)‖ = 1
  simp

theorem qubitZeroState_inner_qubitOneState : ⟪qubitZeroState, qubitOneState⟫_ℂ = 0 := by
  show ⟪EuclideanSpace.single (0 : Fin 2) (1 : ℂ), EuclideanSpace.single (1 : Fin 2) (1 : ℂ)⟫_ℂ = 0
  rw [EuclideanSpace.inner_single_left]
  simp

/-- `EstimationRule 2` is not vacuous: a concrete qubit pure state
generates one. -/
theorem nonempty_estimationRule_two : Nonempty (EstimationRule 2) :=
  ⟨pureStateEstimationRule qubitZeroState qubitZeroState_norm⟩

/-- The projector onto the ray of the very state defining the rule carries
weight `1`: the exact Born-rule certainty case, computed by exact rational
arithmetic only. -/
example :
    (pureStateEstimationRule qubitZeroState qubitZeroState_norm).effectWeight
      (projectionEffect (ℂ ∙ qubitZeroState)) = 1 := by
  show (⟪Gleason.projL (ℂ ∙ qubitZeroState) qubitZeroState, qubitZeroState⟫_ℂ).re = 1
  have hproj : Gleason.projL (ℂ ∙ qubitZeroState) qubitZeroState
      = ⟪qubitZeroState, qubitZeroState⟫_ℂ • qubitZeroState := by
    show (ℂ ∙ qubitZeroState).starProjection qubitZeroState = _
    exact Submodule.starProjection_unit_singleton ℂ qubitZeroState_norm qubitZeroState
  rw [hproj, inner_smul_left, inner_self_eq_norm_sq_to_K, qubitZeroState_norm]
  norm_num

/-- The projector onto the orthogonal ray carries weight `0`: the exact
Born-rule impossibility case. -/
example :
    (pureStateEstimationRule qubitZeroState qubitZeroState_norm).effectWeight
      (projectionEffect (ℂ ∙ qubitOneState)) = 0 := by
  show (⟪Gleason.projL (ℂ ∙ qubitOneState) qubitZeroState, qubitZeroState⟫_ℂ).re = 0
  have hproj : Gleason.projL (ℂ ∙ qubitOneState) qubitZeroState
      = ⟪qubitOneState, qubitZeroState⟫_ℂ • qubitOneState := by
    show (ℂ ∙ qubitOneState).starProjection qubitZeroState = _
    exact Submodule.starProjection_unit_singleton ℂ qubitOneState_norm qubitZeroState
  have hinner : ⟪qubitOneState, qubitZeroState⟫_ℂ = 0 := by
    rw [← inner_conj_symm qubitOneState qubitZeroState, qubitZeroState_inner_qubitOneState]
    simp
  rw [hproj, hinner, zero_smul, inner_zero_left]
  simp

end

end QuantumFoundations.BornRule.EffectPerspectives
