import QuantumFoundations.BornRule.EffectPerspectives.Basic

/-!
# QB2 — Finite effect perspectives

An **effect perspective** is a finite labelled family of effects summing to
the identity: a finite POVM-like family, not a projective decomposition.
Unlike the existing projective `Perspective` (`BornRule.Perspective`), no
nonzero, distinctness, or commutativity hypothesis is imposed: equal
effects at different outcomes, and the zero effect itself, are both
permitted.
-/

namespace QuantumFoundations.BornRule.EffectPerspectives

noncomputable section

/-- A finite effect perspective: a labelled family of effects on
`Gleason.H n` summing to the identity. No nonzero, injectivity,
distinctness, or commutativity hypothesis is required — this is a finite
POVM-like family, not a projective decomposition. -/
structure EffectPerspective (n : ℕ) where
  /-- The number of outcomes. -/
  outcomes : ℕ
  /-- The effect assigned to each outcome. -/
  effects : Fin outcomes → Effect n
  /-- The effects sum to the identity. -/
  sum_eq_one :
    (∑ i, (effects i : Gleason.H n →ₗ[ℂ] Gleason.H n)) = 1

/-! ## QB2.1 — Binary perspective -/

/-- The binary perspective `{T, 1-T}` generated by a single effect `T`. -/
def binaryPerspective {n : ℕ} (T : Effect n) : EffectPerspective n where
  outcomes := 2
  effects := ![T, complementEffect T]
  sum_eq_one := by
    rw [Fin.sum_univ_two]
    show (T : Gleason.H n →ₗ[ℂ] Gleason.H n) + (complementEffect T : Gleason.H n →ₗ[ℂ] Gleason.H n) = 1
    rw [complementEffect_coe]
    abel

@[simp] theorem binaryPerspective_effect_zero {n : ℕ} (T : Effect n) :
    (binaryPerspective T).effects (0 : Fin 2) = T := rfl

@[simp] theorem binaryPerspective_effect_one {n : ℕ} (T : Effect n) :
    (binaryPerspective T).effects (1 : Fin 2) = complementEffect T := rfl

/-! ## QB2.2 — Splitting perspective -/

/-- The sum of two effects, packaged as an effect under the supplied
hypothesis that the sum is itself an effect. -/
def sumEffect {n : ℕ} (S T : Effect n) (hST : Gleason.IsEffect (S.1 + T.1)) :
    Effect n :=
  ⟨S.1 + T.1, hST⟩

@[simp] theorem sumEffect_coe {n : ℕ} (S T : Effect n) (hST : Gleason.IsEffect (S.1 + T.1)) :
    (sumEffect S T hST : Gleason.H n →ₗ[ℂ] Gleason.H n) = S.1 + T.1 := rfl

/-- The splitting perspective `{S, T, 1-S-T}`. -/
def splitPerspective {n : ℕ} (S T : Effect n) (hST : Gleason.IsEffect (S.1 + T.1)) :
    EffectPerspective n where
  outcomes := 3
  effects := ![S, T, complementEffect (sumEffect S T hST)]
  sum_eq_one := by
    rw [Fin.sum_univ_three]
    show (S : Gleason.H n →ₗ[ℂ] Gleason.H n) + (T : Gleason.H n →ₗ[ℂ] Gleason.H n)
        + (complementEffect (sumEffect S T hST) : Gleason.H n →ₗ[ℂ] Gleason.H n) = 1
    rw [complementEffect_coe, sumEffect_coe]
    abel

@[simp] theorem splitPerspective_effect_zero {n : ℕ} (S T : Effect n)
    (hST : Gleason.IsEffect (S.1 + T.1)) :
    (splitPerspective S T hST).effects (0 : Fin 3) = S := rfl

@[simp] theorem splitPerspective_effect_one {n : ℕ} (S T : Effect n)
    (hST : Gleason.IsEffect (S.1 + T.1)) :
    (splitPerspective S T hST).effects (1 : Fin 3) = T := rfl

@[simp] theorem splitPerspective_effect_two {n : ℕ} (S T : Effect n)
    (hST : Gleason.IsEffect (S.1 + T.1)) :
    (splitPerspective S T hST).effects (2 : Fin 3) = complementEffect (sumEffect S T hST) := rfl

/-! ## QB2.3 — Duplicate-zero perspective -/

/-- The perspective `{0, 0, 1}`: two occurrences of the zero effect and one
of the unit effect. Its role is to derive `weight 0 = 0` from refinement
coherence, via a refinement onto `{0, 1}` (`C14a`-style: replacement of one
occurrence at a time). -/
def duplicateZeroPerspective (n : ℕ) : EffectPerspective n where
  outcomes := 3
  effects := ![zeroEffect n, zeroEffect n, oneEffect n]
  sum_eq_one := by
    rw [Fin.sum_univ_three]
    show (zeroEffect n : Gleason.H n →ₗ[ℂ] Gleason.H n) + (zeroEffect n : Gleason.H n →ₗ[ℂ] Gleason.H n)
        + (oneEffect n : Gleason.H n →ₗ[ℂ] Gleason.H n) = 1
    simp

@[simp] theorem duplicateZeroPerspective_effect_zero (n : ℕ) :
    (duplicateZeroPerspective n).effects (0 : Fin 3) = zeroEffect n := rfl

@[simp] theorem duplicateZeroPerspective_effect_one (n : ℕ) :
    (duplicateZeroPerspective n).effects (1 : Fin 3) = zeroEffect n := rfl

@[simp] theorem duplicateZeroPerspective_effect_two (n : ℕ) :
    (duplicateZeroPerspective n).effects (2 : Fin 3) = oneEffect n := rfl

end

end QuantumFoundations.BornRule.EffectPerspectives
