import QuantumFoundations.BornRule.EffectPerspectives.Perspective

/-!
# QB3 — Effect-perspective refinement

A fine effect perspective refines a coarse one when every fine outcome is
assigned to a coarse outcome (`parent`) and every coarse effect equals the
sum of its fine preimage. `parent` need not be surjective: a coarse zero
effect may have an empty preimage.

**Transitivity.** `Refines.trans` composes two refinements via
`parent := parent₂ ∘ parent₁`, reindexing the double finite sum by fixing
the fine outcome and collapsing the inner sum over the middle perspective's
outcomes at the single point `parent₁ i` (`Finset.sum_ite_eq'`), after
swapping summation order (`Finset.sum_comm`). None of QB4–QB10 requires
`Refines.trans`: `contextual_weight_eq_effectWeight` uses
`collapseToChosen`, `effectWeight_zero` uses `duplicateZeroRefinesBinary`,
and `effectWeight_add` uses `splitRefinesBinary`, none of which compose two
refinements — `Refines.trans` was deferred through QB1–QB11 for exactly
this reason, and is added here (downstream-facing, no manuscript role) once
a real consumer (`everettian-probability-lean`) needs refinement chains.
-/

namespace QuantumFoundations.BornRule.EffectPerspectives

noncomputable section

variable {n : ℕ}

/-- A fine effect perspective refines a coarse one via a (not necessarily
surjective) `parent` map, reconstructing every coarse effect as the sum of
its fine preimage. -/
structure Refines (fine coarse : EffectPerspective n) where
  /-- Assigns every fine outcome to a coarse outcome. -/
  parent : Fin fine.outcomes → Fin coarse.outcomes
  /-- Every coarse effect is the sum of its fine preimage. -/
  coarse_eq_fiber_sum :
    ∀ j : Fin coarse.outcomes,
      (coarse.effects j : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin fine.outcomes,
            if parent i = j then (fine.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0

private theorem fin2_cases (x : Fin 2) : x = 0 ∨ x = 1 := by fin_cases x <;> simp

private theorem fin3_cases (x : Fin 3) : x = 0 ∨ x = 1 ∨ x = 2 := by fin_cases x <;> simp

/-! ## QB3.1 — Reflexive refinement -/

/-- Every perspective refines itself, via the identity `parent` map. -/
def Refines.refl (D : EffectPerspective n) : Refines D D where
  parent := id
  coarse_eq_fiber_sum j := by
    rw [show (∑ i : Fin D.outcomes, if (id i : Fin D.outcomes) = j
        then (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
      = ∑ i : Fin D.outcomes, if i = j then (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
        from rfl]
    rw [Finset.sum_ite_eq' Finset.univ j (fun i => (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n))]
    simp

/-! ## QB3.2 — Collapse a context onto one selected effect -/

/-- Collapsing an effect perspective `D` onto the binary perspective
generated by one chosen occurrence `D.effects i`. -/
def collapseToChosen (D : EffectPerspective n) (i : Fin D.outcomes) :
    Refines D (binaryPerspective (D.effects i)) where
  parent := fun k => if k = i then (0 : Fin 2) else (1 : Fin 2)
  coarse_eq_fiber_sum j := by
    rcases fin2_cases j with rfl | rfl
    · simp only [binaryPerspective_effect_zero]
      trans (∑ k : Fin D.outcomes, if k = i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
      · rw [Finset.sum_ite_eq' Finset.univ i (fun k => (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n))]
        simp
      · apply Finset.sum_congr rfl
        intro k _
        by_cases hk : k = i <;> simp [hk]
    · simp only [binaryPerspective_effect_one, complementEffect_coe]
      trans (∑ k : Fin D.outcomes, if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
      · have hsplit :
            (∑ k : Fin D.outcomes, (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n))
              = (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n)
                + (∑ k : Fin D.outcomes, if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0) := by
          calc (∑ k : Fin D.outcomes, (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n))
              = ∑ k : Fin D.outcomes,
                  ((if k = i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
                    + (if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)) :=
                Finset.sum_congr rfl (fun k _ => by by_cases hk : k = i <;> simp [hk])
            _ = (∑ k : Fin D.outcomes, if k = i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
                + (∑ k : Fin D.outcomes, if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0) :=
                Finset.sum_add_distrib
            _ = (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n)
                + (∑ k : Fin D.outcomes, if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0) := by
              rw [Finset.sum_ite_eq' Finset.univ i (fun k => (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n))]
              simp
        rw [D.sum_eq_one] at hsplit
        rw [hsplit]
        abel
      · apply Finset.sum_congr rfl
        intro k _
        by_cases hk : k = i <;> simp [hk]

/-! ## QB3.3 — Split refinement -/

/-- The splitting perspective `{S, T, 1-S-T}` refines the binary
perspective generated by `S + T`. -/
def splitRefinesBinary (S T : Effect n) (hST : Gleason.IsEffect (S.1 + T.1)) :
    Refines (splitPerspective S T hST) (binaryPerspective (sumEffect S T hST)) where
  parent := ![(0 : Fin 2), (0 : Fin 2), (1 : Fin 2)]
  coarse_eq_fiber_sum j := by
    rcases fin2_cases j with rfl | rfl
    · show (sumEffect S T hST : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin 3, if (![(0 : Fin 2), 0, 1] i) = (0 : Fin 2)
            then ((splitPerspective S T hST).effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
      rw [Fin.sum_univ_three, sumEffect_coe]
      simp
    · show (complementEffect (sumEffect S T hST) : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin 3, if (![(0 : Fin 2), 0, 1] i) = (1 : Fin 2)
            then ((splitPerspective S T hST).effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
      rw [Fin.sum_univ_three, complementEffect_coe, sumEffect_coe]
      simp

/-! ## QB3.4 — Duplicate-zero refinement -/

/-- The duplicate-zero perspective `{0, 0, 1}` refines the binary
perspective generated by the zero effect: the coarse zero effect is the
sum `0 + 0`. -/
def duplicateZeroRefinesBinary (n : ℕ) :
    Refines (duplicateZeroPerspective n) (binaryPerspective (zeroEffect n)) where
  parent := ![(0 : Fin 2), (0 : Fin 2), (1 : Fin 2)]
  coarse_eq_fiber_sum j := by
    rcases fin2_cases j with rfl | rfl
    · show (zeroEffect n : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin 3, if (![(0 : Fin 2), 0, 1] i) = (0 : Fin 2)
            then ((duplicateZeroPerspective n).effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
      rw [Fin.sum_univ_three]
      simp
    · show (complementEffect (zeroEffect n) : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin 3, if (![(0 : Fin 2), 0, 1] i) = (1 : Fin 2)
            then ((duplicateZeroPerspective n).effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
      rw [Fin.sum_univ_three]
      simp

/-! ## QB3.5 — Transitivity (downstream-facing; no manuscript role) -/

/-- Composition of two refinements, via `parent := parent₂ ∘ parent₁`. This
declaration serves downstream developments (e.g. `everettian-probability-lean`)
that need to compose refinement chains; it plays no role in the manuscript
*One State, Many Perspectives*. -/
def Refines.trans {fine mid coarse : EffectPerspective n}
    (r1 : Refines fine mid) (r2 : Refines mid coarse) : Refines fine coarse where
  parent := r2.parent ∘ r1.parent
  coarse_eq_fiber_sum j := by
    have step1 := r2.coarse_eq_fiber_sum j
    rw [step1]
    have step2 : ∀ i' : Fin mid.outcomes,
        (if r2.parent i' = j then (mid.effects i' : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
          = ∑ i : Fin fine.outcomes,
              (if r2.parent i' = j then
                (if r1.parent i = i' then (fine.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
              else 0) := by
      intro i'
      by_cases h : r2.parent i' = j
      · simp only [h, if_true]
        exact r1.coarse_eq_fiber_sum i'
      · simp only [h, if_false]
        simp
    trans (∑ i' : Fin mid.outcomes, ∑ i : Fin fine.outcomes,
        (if r2.parent i' = j then
          (if r1.parent i = i' then (fine.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
        else 0))
    · exact Finset.sum_congr rfl (fun i' _ => step2 i')
    · rw [Finset.sum_comm]
      apply Finset.sum_congr rfl
      intro i _
      trans (∑ i' : Fin mid.outcomes,
          if i' = r1.parent i then
            (if r2.parent i' = j then (fine.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
          else 0)
      · apply Finset.sum_congr rfl
        intro i' _
        by_cases h1 : i' = r1.parent i
        · rw [h1]
          simp
        · have h1' : r1.parent i ≠ i' := fun h => h1 h.symm
          simp [h1, h1']
      · rw [Finset.sum_ite_eq' Finset.univ (r1.parent i)
          (fun i' => if r2.parent i' = j then (fine.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)]
        simp [Function.comp_apply]

end

end QuantumFoundations.BornRule.EffectPerspectives
