import QuantumFoundations.BornRule.EffectPerspectives.Perspective

/-!
# QB3 — Effect-perspective refinement

A fine effect perspective refines a coarse one when every fine outcome is
assigned to a coarse outcome (`parent`) and every coarse effect equals the
sum of its fine preimage. `parent` need not be surjective: a coarse zero
effect may have an empty preimage.

**Transitivity deferred.** `Refines.trans` requires reindexing a double
finite sum (merging two conditional sums indexed by different outcome
types, then collapsing the inner sum). The natural proof route was
attempted and repeatedly produced brittle `simp`/`rw` failures
disproportionate to a secondary goal the task explicitly permits deferring
("If finite-sum reindexing becomes disproportionately difficult, defer it
and document the reason. Do not block QB3 on transitivity."). None of
QB4–QB10 requires `Refines.trans`: `contextual_weight_eq_effectWeight` uses
`collapseToChosen`, `effectWeight_zero` uses `duplicateZeroRefinesBinary`,
and `effectWeight_add` uses `splitRefinesBinary`, none of which compose two
refinements. Deferred to future work, not silently dropped.
-/

namespace QuantumFoundations.BornRule.EffectPerspectives

noncomputable section

variable {n : ℕ}

/-- A fine effect perspective refines a coarse one via a (not necessarily
surjective) `parent` map, reconstructing every coarse effect as the sum of
its fine preimage. -/
structure Refines (fine coarse : EffectPerspective n) where
  /-- Assigns every fine outcome to a coarse outcome. -/
  parent : Fin fine.outcomes → Fin coarse.outcomes
  /-- Every coarse effect is the sum of its fine preimage. -/
  coarse_eq_fiber_sum :
    ∀ j : Fin coarse.outcomes,
      (coarse.effects j : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin fine.outcomes,
            if parent i = j then (fine.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0

private theorem fin2_cases (x : Fin 2) : x = 0 ∨ x = 1 := by fin_cases x <;> simp

private theorem fin3_cases (x : Fin 3) : x = 0 ∨ x = 1 ∨ x = 2 := by fin_cases x <;> simp

/-! ## QB3.1 — Reflexive refinement -/

/-- Every perspective refines itself, via the identity `parent` map. -/
def Refines.refl (D : EffectPerspective n) : Refines D D where
  parent := id
  coarse_eq_fiber_sum j := by
    rw [show (∑ i : Fin D.outcomes, if (id i : Fin D.outcomes) = j
        then (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
      = ∑ i : Fin D.outcomes, if i = j then (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
        from rfl]
    rw [Finset.sum_ite_eq' Finset.univ j (fun i => (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n))]
    simp

/-! ## QB3.2 — Collapse a context onto one selected effect -/

/-- Collapsing an effect perspective `D` onto the binary perspective
generated by one chosen occurrence `D.effects i`. -/
def collapseToChosen (D : EffectPerspective n) (i : Fin D.outcomes) :
    Refines D (binaryPerspective (D.effects i)) where
  parent := fun k => if k = i then (0 : Fin 2) else (1 : Fin 2)
  coarse_eq_fiber_sum j := by
    rcases fin2_cases j with rfl | rfl
    · simp only [binaryPerspective_effect_zero]
      trans (∑ k : Fin D.outcomes, if k = i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
      · rw [Finset.sum_ite_eq' Finset.univ i (fun k => (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n))]
        simp
      · apply Finset.sum_congr rfl
        intro k _
        by_cases hk : k = i <;> simp [hk]
    · simp only [binaryPerspective_effect_one, complementEffect_coe]
      trans (∑ k : Fin D.outcomes, if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
      · have hsplit :
            (∑ k : Fin D.outcomes, (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n))
              = (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n)
                + (∑ k : Fin D.outcomes, if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0) := by
          calc (∑ k : Fin D.outcomes, (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n))
              = ∑ k : Fin D.outcomes,
                  ((if k = i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
                    + (if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)) :=
                Finset.sum_congr rfl (fun k _ => by by_cases hk : k = i <;> simp [hk])
            _ = (∑ k : Fin D.outcomes, if k = i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0)
                + (∑ k : Fin D.outcomes, if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0) :=
                Finset.sum_add_distrib
            _ = (D.effects i : Gleason.H n →ₗ[ℂ] Gleason.H n)
                + (∑ k : Fin D.outcomes, if k ≠ i then (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0) := by
              rw [Finset.sum_ite_eq' Finset.univ i (fun k => (D.effects k : Gleason.H n →ₗ[ℂ] Gleason.H n))]
              simp
        rw [D.sum_eq_one] at hsplit
        rw [hsplit]
        abel
      · apply Finset.sum_congr rfl
        intro k _
        by_cases hk : k = i <;> simp [hk]

/-! ## QB3.3 — Split refinement -/

/-- The splitting perspective `{S, T, 1-S-T}` refines the binary
perspective generated by `S + T`. -/
def splitRefinesBinary (S T : Effect n) (hST : Gleason.IsEffect (S.1 + T.1)) :
    Refines (splitPerspective S T hST) (binaryPerspective (sumEffect S T hST)) where
  parent := ![(0 : Fin 2), (0 : Fin 2), (1 : Fin 2)]
  coarse_eq_fiber_sum j := by
    rcases fin2_cases j with rfl | rfl
    · show (sumEffect S T hST : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin 3, if (![(0 : Fin 2), 0, 1] i) = (0 : Fin 2)
            then ((splitPerspective S T hST).effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
      rw [Fin.sum_univ_three, sumEffect_coe]
      simp
    · show (complementEffect (sumEffect S T hST) : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin 3, if (![(0 : Fin 2), 0, 1] i) = (1 : Fin 2)
            then ((splitPerspective S T hST).effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
      rw [Fin.sum_univ_three, complementEffect_coe, sumEffect_coe]
      simp

/-! ## QB3.4 — Duplicate-zero refinement -/

/-- The duplicate-zero perspective `{0, 0, 1}` refines the binary
perspective generated by the zero effect: the coarse zero effect is the
sum `0 + 0`. -/
def duplicateZeroRefinesBinary (n : ℕ) :
    Refines (duplicateZeroPerspective n) (binaryPerspective (zeroEffect n)) where
  parent := ![(0 : Fin 2), (0 : Fin 2), (1 : Fin 2)]
  coarse_eq_fiber_sum j := by
    rcases fin2_cases j with rfl | rfl
    · show (zeroEffect n : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin 3, if (![(0 : Fin 2), 0, 1] i) = (0 : Fin 2)
            then ((duplicateZeroPerspective n).effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
      rw [Fin.sum_univ_three]
      simp
    · show (complementEffect (zeroEffect n) : Gleason.H n →ₗ[ℂ] Gleason.H n)
        = ∑ i : Fin 3, if (![(0 : Fin 2), 0, 1] i) = (1 : Fin 2)
            then ((duplicateZeroPerspective n).effects i : Gleason.H n →ₗ[ℂ] Gleason.H n) else 0
      rw [Fin.sum_univ_three]
      simp

end

end QuantumFoundations.BornRule.EffectPerspectives
