import QuantumFoundations.Selectors.Covariance

/-!
**FR.** # Selectors — S3 : classification (théorème 3), le cœur du module

`IsCovariant σ` équivaut exactement à `σ` appartenant à la famille candidate
`tDensity` pour un `t ∈ [0,1]`. Route élémentaire, sans lemme de Schur ni
théorie des représentations : le stabilisateur du **vecteur** `ψ` (pas du
rayon), engendré par les réflexions de signe et les transpositions de base
fixant `b i₀ = ψ` (`Selectors/Unitaries.lean`), a pour commutant exactement
`ℂ·P_ψ ⊕ ℂ·P_{ψ⊥}`.

Décomposition en lemmes `private`, dans l'ordre :
1. `commute_of_fixes` : `U` fixant `ψ` ⟹ `σ.ρ ψ` commute avec `U`.
2. `offDiag_eq_zero` : coefficients hors diagonale nuls (une réflexion suffit
   par paire, en `k` si `k ≠ i₀`, sinon en `j`).
3. `diag_const_off_psi` : coefficients diagonaux hors `i₀` tous égaux (une
   transposition suffit).
4. `projL_add_projL_compl`, `tDensity_apply_self` : faits techniques sur
   `tDensity`.
5. `eq_tDensity_at_psi` : combine 1–4 avec la trace = 1 pour obtenir, à `ψ`
   fixé, `σ.ρ ψ = tDensity n t ψ` pour un unique `t ∈ [0,1]`.
6. `t_indep_of_psi` : ce `t` ne dépend pas de `ψ` (transitivité unitaire +
   `tDensity_conj`, `Selectors/Unitaries.lean`/`Covariance.lean`).
7. Assemblage : `covariant_iff_tSelector`.

**Piège évité** : le stabilisateur pertinent est celui du **vecteur** `ψ`, pas
du rayon `ℂ · ψ` — les réflexions et transpositions ci-dessus fixent bien
`b i₀` exactement (pas seulement à une phase globale près), ce qui suffit
pour isoler `ℂ · P_ψ ⊕ ℂ · P_{ψ⊥}` sans introduire de phase.

**EN.** # Selectors — S3: classification (Theorem 3), the core of the module

`IsCovariant σ` is exactly equivalent to `σ` belonging to the candidate
family `tDensity` for some `t ∈ [0,1]`. Elementary route, without Schur's
lemma or representation theory: the stabilizer of the **vector** `ψ` (not of
the ray), generated by the sign reflections and basis transpositions fixing
`b i₀ = ψ` (`Selectors/Unitaries.lean`), has commutant exactly
`ℂ·P_ψ ⊕ ℂ·P_{ψ⊥}`.

Decomposed into `private` lemmas, in order:
1. `commute_of_fixes`: `U` fixing `ψ` ⟹ `σ.ρ ψ` commutes with `U`.
2. `offDiag_eq_zero`: off-diagonal coefficients vanish (one reflection
   suffices per pair, at `k` if `k ≠ i₀`, otherwise at `j`).
3. `diag_const_off_psi`: diagonal coefficients off `i₀` are all equal (one
   transposition suffices).
4. `projL_add_projL_compl`, `tDensity_apply_self`: technical facts about
   `tDensity`.
5. `eq_tDensity_at_psi`: combines 1–4 with trace = 1 to get, at a fixed `ψ`,
   `σ.ρ ψ = tDensity n t ψ` for a unique `t ∈ [0,1]`.
6. `t_indep_of_psi`: this `t` does not depend on `ψ` (unitary transitivity +
   `tDensity_conj`, `Selectors/Unitaries.lean`/`Covariance.lean`).
7. Assembly: `covariant_iff_tSelector`.

**Pitfall avoided**: the relevant stabilizer is that of the **vector** `ψ`,
not of the ray `ℂ · ψ` — the reflections and transpositions above do fix
`b i₀` exactly (not merely up to a global phase), which suffices to isolate
`ℂ · P_ψ ⊕ ℂ · P_{ψ⊥}` without introducing a phase.
-/

namespace QuantumFoundations.Selector

open scoped InnerProductSpace
open Gleason
open QuantumFoundations.Uhlhorn (projL_singleton_unit)

noncomputable section

variable {n : ℕ}

/-- **FR.** Si `U` fixe `ψ`, la covariance dit que `σ.ρ ψ` est un point fixe de
la conjugaison par `U` ; en composant par `U` à droite et en simplifiant
`U⁻¹U = id`, cela équivaut à la commutation `σ.ρ ψ ∘ U = U ∘ σ.ρ ψ`.

**EN.** If `U` fixes `ψ`, covariance says `σ.ρ ψ` is a fixed point of
conjugation by `U`; composing on the right by `U` and simplifying
`U⁻¹U = id` turns this into the commutation `σ.ρ ψ ∘ U = U ∘ σ.ρ ψ`. -/
private theorem commute_of_fixes (σ : Selector n) (hσ : IsCovariant σ) {ψ : H n} (hψ : ‖ψ‖ = 1)
    {U : H n ≃ₗᵢ[ℂ] H n} (hU : U ψ = ψ) :
    (σ.ρ ψ) ∘ₗ U.toLinearMap = U.toLinearMap ∘ₗ (σ.ρ ψ) := by
  have hfix : σ.ρ ψ = U.toLinearMap ∘ₗ σ.ρ ψ ∘ₗ U.symm.toLinearMap := by
    have h := hσ U ψ hψ; rwa [hU] at h
  have hUU : U.symm.toLinearMap ∘ₗ U.toLinearMap = LinearMap.id := by ext x; simp
  calc σ.ρ ψ ∘ₗ U.toLinearMap
      = (U.toLinearMap ∘ₗ σ.ρ ψ ∘ₗ U.symm.toLinearMap) ∘ₗ U.toLinearMap := by rw [← hfix]
    _ = U.toLinearMap ∘ₗ σ.ρ ψ ∘ₗ (U.symm.toLinearMap ∘ₗ U.toLinearMap) := by
        rw [LinearMap.comp_assoc, LinearMap.comp_assoc]
    _ = U.toLinearMap ∘ₗ σ.ρ ψ := by rw [hUU, LinearMap.comp_id]

/-- **FR.** Coefficients hors diagonale nuls. Pour `j ≠ k`, choisit la
réflexion au point qui n'est pas `i₀` (au moins un de `j`, `k` en est
différent puisqu'ils sont distincts) ; la covariance donne un signe `±1` sur
un côté de l'égalité et pas sur l'autre, forçant `2 · r = 0`.

**EN.** Off-diagonal coefficients vanish. For `j ≠ k`, choose the reflection
at whichever of `j`, `k` is not `i₀` (at least one of them differs from it,
being distinct); covariance produces a `±1` sign on one side of the equation
and not the other, forcing `2 · r = 0`. -/
private theorem offDiag_eq_zero (σ : Selector n) (hσ : IsCovariant σ) {ψ : H n} (hψ : ‖ψ‖ = 1)
    (b : OrthonormalBasis (Fin n) ℂ (H n)) (i₀ : Fin n) (hbi₀ : b i₀ = ψ)
    {j k : Fin n} (hjk : j ≠ k) :
    ⟪b j, σ.ρ ψ (b k)⟫_ℂ = 0 := by
  by_cases hk : k = i₀
  · have hji0 : j ≠ i₀ := hk ▸ hjk
    have hkj : k ≠ j := by rw [hk]; exact Ne.symm hji0
    have hUfix : reflIso b j ψ = ψ := by rw [← hbi₀, reflIso_apply, if_neg (Ne.symm hji0)]
    have hcomm := commute_of_fixes σ hσ hψ hUfix
    have happly : (σ.ρ ψ) (reflIso b j (b k)) = reflIso b j ((σ.ρ ψ) (b k)) := by
      have h := congrArg (fun f : H n →ₗ[ℂ] H n => f (b k)) hcomm
      simpa using h
    rw [reflIso_apply, if_neg hkj] at happly
    have hinner := congrArg (fun w => ⟪b j, w⟫_ℂ) happly
    rw [adjoint_apply, reflIso_symm_apply, reflIso_apply, if_pos rfl, inner_neg_left] at hinner
    linear_combination hinner / 2
  · have hUfix : reflIso b k ψ = ψ := by rw [← hbi₀, reflIso_apply, if_neg (Ne.symm hk)]
    have hcomm := commute_of_fixes σ hσ hψ hUfix
    have happly : (σ.ρ ψ) (reflIso b k (b k)) = reflIso b k ((σ.ρ ψ) (b k)) := by
      have h := congrArg (fun f : H n →ₗ[ℂ] H n => f (b k)) hcomm
      simpa using h
    rw [reflIso_apply, if_pos rfl, map_neg] at happly
    have hinner := congrArg (fun w => ⟪b j, w⟫_ℂ) happly
    rw [inner_neg_right, adjoint_apply, reflIso_symm_apply, reflIso_apply, if_neg hjk] at hinner
    linear_combination -hinner / 2

/-- **FR.** Coefficients diagonaux hors `i₀` tous égaux. La transposition
`i ↔ j` (les deux `≠ i₀`) fixe `ψ`, échange `b i` et `b j` ; la covariance
transporte directement le coefficient de l'un vers l'autre.

**EN.** Off-`i₀` diagonal coefficients are all equal. The transposition
`i ↔ j` (both `≠ i₀`) fixes `ψ`, swaps `b i` and `b j`; covariance directly
transports the coefficient of one into the other. -/
private theorem diag_const_off_psi (σ : Selector n) (hσ : IsCovariant σ) {ψ : H n} (hψ : ‖ψ‖ = 1)
    (b : OrthonormalBasis (Fin n) ℂ (H n)) (i₀ : Fin n) (hbi₀ : b i₀ = ψ)
    {i j : Fin n} (hi0 : i ≠ i₀) (hj0 : j ≠ i₀) :
    ⟪b i, σ.ρ ψ (b i)⟫_ℂ = ⟪b j, σ.ρ ψ (b j)⟫_ℂ := by
  by_cases hij : i = j
  · rw [hij]
  · have hUfix : swapIso b i j ψ = ψ := by
      rw [← hbi₀, swapIso_apply, Equiv.swap_apply_of_ne_of_ne (Ne.symm hi0) (Ne.symm hj0)]
    have hcomm := commute_of_fixes σ hσ hψ hUfix
    have happly : (σ.ρ ψ) (swapIso b i j (b i)) = swapIso b i j ((σ.ρ ψ) (b i)) := by
      have h := congrArg (fun f : H n →ₗ[ℂ] H n => f (b i)) hcomm
      simpa using h
    rw [swapIso_apply, Equiv.swap_apply_left] at happly
    have hinner := congrArg (fun w => ⟪b j, w⟫_ℂ) happly
    rw [adjoint_apply, swapIso_symm, swapIso_apply, Equiv.swap_apply_right] at hinner
    exact hinner.symm

/-- **FR.** `P_A + P_{Aᗮ} = id`, la résolution de l'identité en deux blocs
orthogonaux (`projL_sup_of_isOrtho` + `starProjection_top`).

**EN.** `P_A + P_{Aᗮ} = id`, the resolution of the identity into two
orthogonal blocks (`projL_sup_of_isOrtho` + `starProjection_top`). -/
private theorem projL_add_projL_compl (A : Submodule ℂ (H n)) :
    projL A + projL Aᗮ = LinearMap.id := by
  have hortho : A ⟂ Aᗮ := Submodule.le_orthogonal_orthogonal _
  have hsup : A ⊔ Aᗮ = ⊤ := Submodule.sup_orthogonal_of_hasOrthogonalProjection
  have hproj_sum : projL (A ⊔ Aᗮ) = projL A + projL Aᗮ := Gleason.projL_sup_of_isOrtho hortho
  rw [hsup] at hproj_sum
  rw [← hproj_sum]
  show ((⊤ : Submodule ℂ (H n)).starProjection : H n →L[ℂ] H n).toLinearMap = LinearMap.id
  rw [Submodule.starProjection_top]
  rfl

/-- **FR.** `tDensity n r φ φ = r · φ` : au point `φ` lui-même, seul le terme
`P_φ` contribue (`P_{φᗮ} φ = 0` par `projL_add_projL_compl`).

**EN.** `tDensity n r φ φ = r · φ`: at the point `φ` itself, only the `P_φ`
term contributes (`P_{φᗮ} φ = 0` by `projL_add_projL_compl`). -/
private theorem tDensity_apply_self {φ : H n} (hφ : ‖φ‖ = 1) (r : ℝ) :
    tDensity n r φ φ = (r : ℂ) • φ := by
  unfold tDensity
  rw [LinearMap.add_apply, LinearMap.smul_apply, LinearMap.smul_apply]
  have hp1 : projL (ℂ ∙ φ) φ = φ := by
    rw [projL_singleton_unit φ φ hφ, inner_self_eq_norm_sq_to_K, hφ]
    norm_num
  have hp2 : projL (ℂ ∙ φ) φ + projL (ℂ ∙ φ)ᗮ φ = φ :=
    congrArg (· φ) (projL_add_projL_compl (ℂ ∙ φ))
  have hp2' : projL (ℂ ∙ φ)ᗮ φ = 0 := by
    rw [hp1] at hp2
    exact add_left_cancel (hp2.trans (add_zero φ).symm)
  rw [hp1, hp2', smul_zero, add_zero]

/-- **FR.** À `ψ` fixé, `σ.ρ ψ` est exactement `tDensity n t ψ` pour un
`t ∈ [0,1]`. Étend `ψ` en base orthonormée `b` (`b i₀ = ψ`) ; `offDiag_eq_zero`
et `diag_const_off_psi` donnent la représentation diagonale
`σ.ρ ψ (b k) = r_k · b k` (`r_{i₀} =: t`, `r_k =: s` pour `k ≠ i₀`) ; la trace
`= 1` (`LinearMap.trace_eq_sum_inner`) donne `t + (n-1) s = 1`, d'où
`s = (1-t)/(n-1)` (ici `hn : 2 ≤ n` est indispensable) ; la positivité donne
`0 ≤ t`, `0 ≤ s`, d'où `t ≤ 1`.

**EN.** At a fixed `ψ`, `σ.ρ ψ` is exactly `tDensity n t ψ` for some
`t ∈ [0,1]`. Extend `ψ` to an orthonormal basis `b` (`b i₀ = ψ`);
`offDiag_eq_zero` and `diag_const_off_psi` give the diagonal representation
`σ.ρ ψ (b k) = r_k · b k` (`r_{i₀} =: t`, `r_k =: s` for `k ≠ i₀`); the trace
`= 1` (`LinearMap.trace_eq_sum_inner`) gives `t + (n-1) s = 1`, hence
`s = (1-t)/(n-1)` (here `hn : 2 ≤ n` is essential); positivity gives `0 ≤ t`,
`0 ≤ s`, hence `t ≤ 1`. -/
private theorem eq_tDensity_at_psi (hn : 2 ≤ n) (σ : Selector n) (hσ : IsCovariant σ)
    {ψ : H n} (hψ : ‖ψ‖ = 1) :
    ∃ t : ℝ, 0 ≤ t ∧ t ≤ 1 ∧ σ.ρ ψ = tDensity n t ψ := by
  have hn1 : 1 ≤ n := le_trans (by norm_num) hn
  obtain ⟨b, hb⟩ := exists_orthonormalBasis_extension_complex hn1 (fun _ : Fin 1 => ψ)
    (by rw [orthonormal_iff_ite]; intro i j; fin_cases i; fin_cases j; simp [hψ])
  set i₀ : Fin n := Fin.castLE hn1 (0 : Fin 1) with hi0_def
  have hbi₀ : b i₀ = ψ := hb 0
  haveI : Nontrivial (Fin n) := Fin.nontrivial_iff_two_le.mpr hn
  obtain ⟨i₁, hi₁⟩ := exists_ne i₀
  set t : ℝ := (⟪b i₀, σ.ρ ψ (b i₀)⟫_ℂ).re with ht_def
  set s : ℝ := (⟪b i₁, σ.ρ ψ (b i₁)⟫_ℂ).re with hs_def
  have hsymm : LinearMap.IsSymmetric (σ.ρ ψ) := (σ.isDensity ψ hψ).symmetric
  have hreal : ∀ k : Fin n, ⟪b k, σ.ρ ψ (b k)⟫_ℂ = ((⟪b k, σ.ρ ψ (b k)⟫_ℂ).re : ℂ) := by
    intro k
    have hconjeq : (starRingEnd ℂ) ⟪b k, σ.ρ ψ (b k)⟫_ℂ = ⟪b k, σ.ρ ψ (b k)⟫_ℂ := by
      rw [inner_conj_symm, hsymm (b k) (b k)]
    exact (Complex.conj_eq_iff_re.mp hconjeq).symm
  have ht_eq : ⟪b i₀, σ.ρ ψ (b i₀)⟫_ℂ = (t : ℂ) := hreal i₀
  have hs_eq' : ∀ i : Fin n, i ≠ i₀ → ⟪b i, σ.ρ ψ (b i)⟫_ℂ = (s : ℂ) := by
    intro i hi
    rw [hreal i]
    have hconst := diag_const_off_psi σ hσ hψ b i₀ hbi₀ hi hi₁
    rw [hconst]
  have hdiag : ∀ k : Fin n, σ.ρ ψ (b k) = ⟪b k, σ.ρ ψ (b k)⟫_ℂ • b k := by
    intro k
    conv_lhs => rw [← OrthonormalBasis.sum_repr b (σ.ρ ψ (b k))]
    rw [Finset.sum_eq_single k]
    · rw [OrthonormalBasis.repr_apply_apply]
    · intro j _ hjk
      rw [OrthonormalBasis.repr_apply_apply, offDiag_eq_zero σ hσ hψ b i₀ hbi₀ hjk, zero_smul]
    · intro h; exact absurd (Finset.mem_univ k) h
  have hn1' : (0 : ℝ) < (n : ℝ) - 1 := by
    have h2n : (2 : ℝ) ≤ (n : ℝ) := by exact_mod_cast hn
    linarith
  have htrace : LinearMap.trace ℂ (H n) (σ.ρ ψ) = 1 := (σ.isDensity ψ hψ).trace_one
  have htrace_sum : LinearMap.trace ℂ (H n) (σ.ρ ψ) = ∑ k, ⟪b k, σ.ρ ψ (b k)⟫_ℂ :=
    LinearMap.trace_eq_sum_inner _ b
  have hsplit : ⟪b i₀, σ.ρ ψ (b i₀)⟫_ℂ + ∑ k ∈ Finset.univ.erase i₀, ⟪b k, σ.ρ ψ (b k)⟫_ℂ
      = ∑ k, ⟪b k, σ.ρ ψ (b k)⟫_ℂ :=
    Finset.add_sum_erase Finset.univ (fun k => ⟪b k, σ.ρ ψ (b k)⟫_ℂ) (Finset.mem_univ i₀)
  have hrest : ∑ k ∈ Finset.univ.erase i₀, ⟪b k, σ.ρ ψ (b k)⟫_ℂ
      = (Finset.univ.erase i₀).card • (s : ℂ) := by
    apply Finset.sum_congr rfl (fun k hk => hs_eq' k (Finset.mem_erase.mp hk).1) |>.trans
    rw [Finset.sum_const]
  have hcard : (Finset.univ.erase i₀ : Finset (Fin n)).card = n - 1 := by
    rw [Finset.card_erase_of_mem (Finset.mem_univ i₀), Finset.card_univ, Fintype.card_fin]
  have htrace_eq : (t : ℂ) + ((n - 1 : ℕ) : ℂ) * (s : ℂ) = 1 := by
    have h := hsplit
    rw [ht_eq, hrest, hcard, nsmul_eq_mul] at h
    rw [h, ← htrace_sum, htrace]
  have hs_val : s = (1 - t) / ((n : ℝ) - 1) := by
    have hcast : ((n - 1 : ℕ) : ℂ) = (n : ℂ) - 1 := by
      have h : (n - 1 : ℕ) + 1 = n := Nat.succ_pred_eq_of_pos hn1
      have h2 : ((n - 1 : ℕ) : ℂ) + 1 = (n : ℂ) := by exact_mod_cast h
      linear_combination h2
    rw [hcast] at htrace_eq
    have hreal2 : t + ((n : ℝ) - 1) * s = 1 := by exact_mod_cast htrace_eq
    field_simp
    linarith
  refine ⟨t, ?_, ?_, ?_⟩
  · have hthis := (σ.isDensity ψ hψ).nonneg (b i₀)
    rw [hsymm (b i₀) (b i₀), ht_eq] at hthis
    simpa using hthis
  · have hs_nonneg : 0 ≤ s := by
      have hthis := (σ.isDensity ψ hψ).nonneg (b i₁)
      rw [hsymm (b i₁) (b i₁), hs_eq' i₁ hi₁] at hthis
      simpa using hthis
    have hkey : s * ((n : ℝ) - 1) = 1 - t := by rw [hs_val]; field_simp
    nlinarith [mul_nonneg hs_nonneg hn1'.le, hkey]
  · apply b.toBasis.ext
    intro k
    rw [OrthonormalBasis.coe_toBasis]
    by_cases hk : k = i₀
    · rw [hdiag k, hk, ht_eq, hbi₀]
      show (t : ℂ) • ψ = tDensity n t ψ ψ
      unfold tDensity
      rw [LinearMap.add_apply, LinearMap.smul_apply, LinearMap.smul_apply]
      have hp1 : projL (ℂ ∙ ψ) ψ = ψ := by
        rw [projL_singleton_unit ψ ψ hψ, inner_self_eq_norm_sq_to_K, hψ]
        norm_num
      have hp2 : projL (ℂ ∙ ψ) ψ + projL (ℂ ∙ ψ)ᗮ ψ = ψ :=
        congrArg (· ψ) (projL_add_projL_compl (ℂ ∙ ψ))
      have hp2' : projL (ℂ ∙ ψ)ᗮ ψ = 0 := by
        rw [hp1] at hp2
        exact add_left_cancel (hp2.trans (add_zero ψ).symm)
      rw [hp1, hp2', smul_zero, add_zero]
    · rw [hdiag k, hs_eq' k hk]
      show (s : ℂ) • b k = tDensity n t ψ (b k)
      unfold tDensity
      rw [LinearMap.add_apply, LinearMap.smul_apply, LinearMap.smul_apply]
      have hbk_perp : ⟪ψ, b k⟫_ℂ = 0 := by
        rw [← hbi₀]
        exact b.inner_eq_ite i₀ k ▸ (if_neg (Ne.symm hk))
      have hp1 : projL (ℂ ∙ ψ) (b k) = 0 := by
        rw [projL_singleton_unit ψ (b k) hψ, hbk_perp, zero_smul]
      have hp2 : projL (ℂ ∙ ψ) (b k) + projL (ℂ ∙ ψ)ᗮ (b k) = b k :=
        congrArg (· (b k)) (projL_add_projL_compl (ℂ ∙ ψ))
      have hp2' : projL (ℂ ∙ ψ)ᗮ (b k) = b k := by
        rw [hp1, zero_add] at hp2; exact hp2
      rw [hp1, hp2', smul_zero, zero_add, hs_val]

/-- **FR.** Le `t` de `eq_tDensity_at_psi` ne dépend pas de `ψ` : la
transitivité unitaire relie `ψ` à `φ` par `U`, la covariance transporte
`σ.ρ ψ = tDensity n t ψ` en `σ.ρ φ = tDensity n t φ` (via `tDensity_conj`),
et l'évaluation en `φ` (`tDensity_apply_self`) l'identifie à `s`.

**EN.** The `t` of `eq_tDensity_at_psi` does not depend on `ψ`: unitary
transitivity relates `ψ` to `φ` via `U`, covariance transports
`σ.ρ ψ = tDensity n t ψ` into `σ.ρ φ = tDensity n t φ` (via `tDensity_conj`),
and evaluating at `φ` (`tDensity_apply_self`) identifies it with `s`. -/
private theorem t_indep_of_psi (σ : Selector n) (hσ : IsCovariant σ)
    {ψ φ : H n} (hψ : ‖ψ‖ = 1) (hφ : ‖φ‖ = 1)
    {t s : ℝ} (hψeq : σ.ρ ψ = tDensity n t ψ) (hφeq : σ.ρ φ = tDensity n s φ) :
    t = s := by
  obtain ⟨U, hU⟩ := exists_isometry_apply_eq hψ hφ
  have hcov := hσ U ψ hψ
  rw [hU, hψeq, ← tDensity_conj U t ψ, hU] at hcov
  rw [hφeq] at hcov
  have heval := congrArg (fun f : H n →ₗ[ℂ] H n => ⟪φ, f φ⟫_ℂ) hcov
  simp only [tDensity_apply_self hφ, inner_smul_right] at heval
  have hφφ : ⟪φ, φ⟫_ℂ = 1 := by
    rw [inner_self_eq_norm_sq_to_K, hφ]; norm_num
  rw [hφφ, mul_one, mul_one] at heval
  exact_mod_cast heval.symm

/--
**FR.** **Théorème 3 (classification)** : un sélecteur est unitairement
covariant si et seulement s'il appartient à la famille candidate `tDensity`
pour un paramètre `t ∈ [0,1]`.

**EN.** **Theorem 3 (classification)**: a selector is unitarily covariant if
and only if it belongs to the candidate family `tDensity` for some parameter
`t ∈ [0,1]`.
-/
theorem covariant_iff_tSelector (hn : 2 ≤ n) (σ : Selector n) :
    IsCovariant σ ↔ ∃ t : ℝ, 0 ≤ t ∧ t ≤ 1 ∧
      ∀ ψ : H n, ‖ψ‖ = 1 → σ.ρ ψ = tDensity n t ψ := by
  constructor
  · intro hσ
    have hψ₀ : ‖(EuclideanSpace.single (⟨0, by omega⟩ : Fin n) (1 : ℂ) : H n)‖ = 1 := by
      rw [PiLp.norm_single]; norm_num
    obtain ⟨t, ht0, ht1, hψ₀eq⟩ := eq_tDensity_at_psi hn σ hσ hψ₀
    refine ⟨t, ht0, ht1, fun ψ hψ => ?_⟩
    obtain ⟨t', ht0', ht1', hψeq⟩ := eq_tDensity_at_psi hn σ hσ hψ
    have hteq : t' = t := t_indep_of_psi σ hσ hψ hψ₀ hψeq hψ₀eq
    rwa [hteq] at hψeq
  · rintro ⟨t, ht0, ht1, heq⟩ U ψ hψ
    have hUψ : ‖U ψ‖ = 1 := by rw [LinearIsometryEquiv.norm_map]; exact hψ
    rw [heq (U ψ) hUψ, tDensity_conj, ← heq ψ hψ]

end
end QuantumFoundations.Selector
