import QuantumFoundations.Selectors.Covariance

/-!
**FR.** # Selectors — S3 : classification (théorème 3), le cœur du module

`IsCovariant σ` équivaut exactement à `σ` appartenant à la famille candidate
`tDensity` pour un `t ∈ [0,1]`. Route élémentaire, sans lemme de Schur ni
théorie des représentations : stabilisateur du **vecteur** `ψ` (pas du rayon),
engendré par des réflexions de signe et des transpositions de base fixant
`b i₀ = ψ` (`Selectors/Unitaries.lean`), dont le commutant est exactement
`ℂ·P_ψ ⊕ ℂ·P_{ψ⊥}`.

**EN.** # Selectors — S3: classification (Theorem 3), the core of the module

`IsCovariant σ` is exactly equivalent to `σ` belonging to the candidate family
`tDensity` for some `t ∈ [0,1]`. Elementary route, without Schur's lemma or
representation theory: the stabilizer of the **vector** `ψ` (not of the ray),
generated by sign reflections and basis transpositions fixing `b i₀ = ψ`
(`Selectors/Unitaries.lean`), whose commutant is exactly `ℂ·P_ψ ⊕ ℂ·P_{ψ⊥}`.
-/

namespace QuantumFoundations.Selector

open scoped InnerProductSpace
open Gleason

noncomputable section

variable {n : ℕ}

/--
**FR.** **Théorème 3 (classification)** : un sélecteur est unitairement
covariant si et seulement s'il appartient à la famille candidate `tDensity`
pour un paramètre `t ∈ [0,1]`.

**EN.** **Theorem 3 (classification)**: a selector is unitarily covariant if
and only if it belongs to the candidate family `tDensity` for some parameter
`t ∈ [0,1]`.
-/
theorem covariant_iff_tSelector (hn : 2 ≤ n) (σ : Selector n) :
    IsCovariant σ ↔ ∃ t : ℝ, 0 ≤ t ∧ t ≤ 1 ∧
      ∀ ψ : H n, ‖ψ‖ = 1 → σ.ρ ψ = tDensity n t ψ := by
  sorry

end
end QuantumFoundations.Selector
