import QuantumFoundations.Selectors.BasisStabilizer
import QuantumFoundations.BornRule.Perspective

/-!
**FR.** # Selectors — Module B, dépendance structurelle générale : perspectives

Généralise `dephasedDensity`/`dephasingSelector` (`Dephasing.lean`, basés
sur une base orthonormée, cellules de dimension 1) à une **perspective**
`D : Perspective n` quelconque (`QuantumFoundations.BornRule.Perspective`),
famille finie de sous-espaces orthogonaux non nuls dont la somme directe
est l'espace entier, sans restriction de dimension par cellule.

`perspectiveDephasedDensity D ψ := ∑ c ∈ D.cells, P_c ∘ (|ψ⟩⟨ψ|) ∘ P_c`
est l'application de « pinçage » (« pinching ») standard : la partie
bloc-diagonale de la densité pure `|ψ⟩⟨ψ|` relativement à la décomposition
orthogonale `D`. C'est une densité valide pour tout `ψ` unitaire
(`perspectiveDephasedDensity_isDensity`), la preuve de trace `= 1` route
par le rang-un (`InnerProductSpace.rankOne`/`trace_rankOne`) pour chaque
terme, puis par le théorème de Pythagore fini déjà public
(`sum_sq_projL_of_pairwise_isOrtho`, `BornRule/Perspective.lean`).

**Compatibilité** : pour la perspective engendrée par une base orthonormée
(`basisPerspective b`, cellules de dimension 1), le pinçage coïncide
EXACTEMENT avec `dephasedDensity b ψ`
(`perspectiveDephasedDensity_basisPerspective`) — la construction de ce
fichier généralise fidèlement celle de `Dephasing.lean`, elle ne la
remplace pas.

**EN.** # Selectors — Module B, general structural dependence: perspectives

Generalizes `dephasedDensity`/`dephasingSelector` (`Dephasing.lean`, based
on an orthonormal basis, dimension-1 cells) to an arbitrary **perspective**
`D : Perspective n` (`QuantumFoundations.BornRule.Perspective`), a finite
family of nonzero orthogonal subspaces whose direct sum is the whole
space, with no restriction on cell dimension.

`perspectiveDephasedDensity D ψ := ∑ c ∈ D.cells, P_c ∘ (|ψ⟩⟨ψ|) ∘ P_c` is
the standard "pinching" map: the block-diagonal part of the pure density
`|ψ⟩⟨ψ|` relative to the orthogonal decomposition `D`. It is a valid
density for every unit `ψ` (`perspectiveDephasedDensity_isDensity`); the
trace `= 1` proof routes through the rank-one operator
(`InnerProductSpace.rankOne`/`trace_rankOne`) for each term, then the
already-public finite Pythagorean theorem
(`sum_sq_projL_of_pairwise_isOrtho`, `BornRule/Perspective.lean`).

**Compatibility**: for the perspective generated by an orthonormal basis
(`basisPerspective b`, dimension-1 cells), pinching coincides EXACTLY with
`dephasedDensity b ψ` (`perspectiveDephasedDensity_basisPerspective`) —
this file's construction faithfully generalizes `Dephasing.lean`'s, it
does not replace it.
-/

namespace QuantumFoundations.Selector

open scoped InnerProductSpace
open Gleason
open QuantumFoundations.BornRule

noncomputable section

variable {n : ℕ}

/--
**FR.** La cellule d'une `Perspective D`, comme sous-type — nécessaire
pour indexer un groupe de permutation agissant sur les cellules
(stabilisateurs de sous-groupe, `PerspectiveStabilizer.lean`).

**EN.** The cell of a `Perspective D`, as a subtype — needed to index a
permutation group acting on the cells (subgroup stabilizers,
`PerspectiveStabilizer.lean`).
-/
def Perspective.Cell (D : Perspective n) := {c : Submodule ℂ (H n) // c ∈ D.cells}

instance (D : Perspective n) : Fintype (Perspective.Cell D) := by
  unfold Perspective.Cell; infer_instance

instance (D : Perspective n) : DecidableEq (Perspective.Cell D) := by
  unfold Perspective.Cell; classical infer_instance

/-- The orthogonal projection onto a cell of `D`. -/
def cellProjection (D : Perspective n) (c : Perspective.Cell D) : H n →ₗ[ℂ] H n :=
  projL (c.1 : Submodule ℂ (H n))

private theorem projL_eq_starProjection (A : Submodule ℂ (H n)) (x : H n) :
    projL A x = A.starProjection x := rfl

private theorem projL_isSymmetric' (A : Submodule ℂ (H n)) (x y : H n) :
    ⟪projL A x, y⟫_ℂ = ⟪x, projL A y⟫_ℂ := by
  rw [projL_eq_starProjection, projL_eq_starProjection]
  exact Submodule.starProjection_isSymmetric A x y

/-- Sandwiching the pure Born density between the projection onto a cell
`c` and itself is exactly the rank-one operator `|P_c ψ⟩⟨P_c ψ|`, for unit `ψ`. -/
private theorem cellSandwich_eq_rankOne (c : Submodule ℂ (H n)) {ψ : H n} (hψ : ‖ψ‖ = 1) :
    projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c
      = (InnerProductSpace.rankOne ℂ (projL c ψ) (projL c ψ) : H n →ₗ[ℂ] H n) := by
  apply LinearMap.ext
  intro x
  show projL c (projL (ℂ ∙ ψ) (projL c x)) = _
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit ψ (projL c x) hψ, map_smul]
  have hrk : (InnerProductSpace.rankOne ℂ (projL c ψ) (projL c ψ) : H n →ₗ[ℂ] H n) x
      = ⟪projL c ψ, x⟫_ℂ • projL c ψ := InnerProductSpace.rankOne_apply _ _ _
  rw [hrk]
  congr 1
  exact (projL_isSymmetric' c ψ x).symm

private theorem cellSandwich_isSymmetric (c : Submodule ℂ (H n)) (ψ : H n) :
    LinearMap.IsSymmetric (projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c) := by
  intro x y
  show ⟪projL c (projL (ℂ ∙ ψ) (projL c x)), y⟫_ℂ = ⟪x, projL c (projL (ℂ ∙ ψ) (projL c y))⟫_ℂ
  rw [projL_isSymmetric' c (projL (ℂ ∙ ψ) (projL c x)) y,
    projL_isSymmetric' (ℂ ∙ ψ) (projL c x) (projL c y),
    projL_isSymmetric' c x (projL (ℂ ∙ ψ) (projL c y))]

private theorem cellSandwich_nonneg (c : Submodule ℂ (H n)) (ψ x : H n) :
    0 ≤ (⟪(projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c) x, x⟫_ℂ).re := by
  show 0 ≤ (⟪projL c (projL (ℂ ∙ ψ) (projL c x)), x⟫_ℂ).re
  rw [projL_isSymmetric' c (projL (ℂ ∙ ψ) (projL c x)) x, projL_eq_starProjection]
  exact Submodule.re_inner_starProjection_nonneg (ℂ ∙ ψ) (projL c x)

/--
**FR.** La densité de pinçage relativement à `D`, au point `ψ` :
`∑ c ∈ D.cells, P_c |ψ⟩⟨ψ| P_c`. Définition TOTALE (valeur poubelle pour
`ψ` non unitaire) ; la validité en tant que densité est
`perspectiveDephasedDensity_isDensity`.

**EN.** The pinching density relative to `D`, at `ψ`:
`∑ c ∈ D.cells, P_c |ψ⟩⟨ψ| P_c`. TOTAL definition (junk value for
non-unit `ψ`); validity as a density is
`perspectiveDephasedDensity_isDensity`.
-/
def perspectiveDephasedDensity (D : Perspective n) (ψ : H n) : H n →ₗ[ℂ] H n :=
  ∑ c ∈ D.cells, projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c

theorem perspectiveDephasedDensity_isSymmetric (D : Perspective n) (ψ : H n) :
    LinearMap.IsSymmetric (perspectiveDephasedDensity D ψ) := by
  intro x y
  show ⟪(∑ c ∈ D.cells, projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c) x, y⟫_ℂ
    = ⟪x, (∑ c ∈ D.cells, projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c) y⟫_ℂ
  simp_rw [LinearMap.sum_apply, sum_inner, inner_sum]
  apply Finset.sum_congr rfl
  intro c _
  exact cellSandwich_isSymmetric c ψ x y

theorem perspectiveDephasedDensity_nonneg (D : Perspective n) (ψ x : H n) :
    0 ≤ (⟪perspectiveDephasedDensity D ψ x, x⟫_ℂ).re := by
  show 0 ≤ (⟪(∑ c ∈ D.cells, projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c) x, x⟫_ℂ).re
  simp_rw [LinearMap.sum_apply, sum_inner]
  rw [Complex.re_sum]
  apply Finset.sum_nonneg
  intro c _
  exact cellSandwich_nonneg c ψ x

private theorem cells_sup_eq_top (D : Perspective n) : D.cells.sup id = ⊤ := by
  rw [Finset.sup_eq_sSup_image, Set.image_id]
  exact D.span

/--
**FR.** Trace `= 1` : chaque terme de cellule a pour trace `‖P_c ψ‖^2`
(rang-un, `InnerProductSpace.trace_rankOne`), et la somme de ces normes
au carré vaut `‖ψ‖^2 = 1` par le théorème de Pythagore fini sur la
famille orthogonale `D.cells` (`sum_sq_projL_of_pairwise_isOrtho`).

**EN.** Trace `= 1`: each cell term has trace `‖P_c ψ‖^2` (rank-one,
`InnerProductSpace.trace_rankOne`), and the sum of these squared norms
equals `‖ψ‖^2 = 1` by the finite Pythagorean theorem on the orthogonal
family `D.cells` (`sum_sq_projL_of_pairwise_isOrtho`).
-/
theorem perspectiveDephasedDensity_trace (D : Perspective n) {ψ : H n} (hψ : ‖ψ‖ = 1) :
    LinearMap.trace ℂ (H n) (perspectiveDephasedDensity D ψ) = 1 := by
  show LinearMap.trace ℂ (H n) (∑ c ∈ D.cells, projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c) = 1
  rw [map_sum]
  have hterm : ∀ c ∈ D.cells, LinearMap.trace ℂ (H n) (projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c)
      = ((‖projL c ψ‖ ^ 2 : ℝ) : ℂ) := by
    intro c _
    rw [cellSandwich_eq_rankOne c hψ, InnerProductSpace.trace_rankOne,
      inner_self_eq_norm_sq_to_K (𝕜 := ℂ)]
    norm_cast
  rw [Finset.sum_congr rfl hterm, ← Complex.ofReal_sum]
  have hpyth : ∑ c ∈ D.cells, ‖projL c ψ‖ ^ 2 = ‖ψ‖ ^ 2 := by
    have := sum_sq_projL_of_pairwise_isOrtho D.cells
      (fun c hc c' hc' hne => Submodule.isOrtho_iff_le.mpr (D.ortho c hc c' hc' hne)) ψ
    rw [cells_sup_eq_top D] at this
    have hid : projL (⊤ : Submodule ℂ (H n)) ψ = ψ := by
      show (⊤ : Submodule ℂ (H n)).starProjection ψ = ψ
      exact Submodule.starProjection_eq_self_iff.mpr Submodule.mem_top
    rw [hid] at this
    exact this.symm
  rw [hpyth, hψ]
  norm_num

theorem perspectiveDephasedDensity_isDensity (D : Perspective n) {ψ : H n} (hψ : ‖ψ‖ = 1) :
    IsDensityOperator (perspectiveDephasedDensity D ψ) :=
  ⟨perspectiveDephasedDensity_isSymmetric D ψ, perspectiveDephasedDensity_nonneg D ψ,
    perspectiveDephasedDensity_trace D hψ⟩

/-- The dephasing selector associated with a perspective `D`. -/
noncomputable def perspectiveDephasingSelector (D : Perspective n) : Selector n where
  ρ := perspectiveDephasedDensity D
  isDensity := fun _ hψ => perspectiveDephasedDensity_isDensity D hψ

end

/--
**FR.** Compatibilité avec le sélecteur déphasant fondé sur une base : pour
la perspective portée par les droites d'une base `b`, le pinçage
coïncide exactement avec `dephasedDensity`.

**EN.** Compatibility with the basis-derived dephasing selector: for the
perspective made of a basis's lines, pinching coincides exactly with
`dephasedDensity`.
-/
theorem perspectiveDephasedDensity_basisPerspective (b : OrthonormalBasis (Fin n) ℂ (H n))
    {ψ : H n} (hψ : ‖ψ‖ = 1) :
    perspectiveDephasedDensity (basisPerspective b) ψ = dephasedDensity b ψ := by
  show (∑ c ∈ (basisPerspective b).cells, projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c) = _
  show (∑ c ∈ Finset.univ.image (fun i => (ℂ ∙ (b i : H n) : Submodule ℂ (H n))),
    projL c ∘ₗ projL (ℂ ∙ ψ) ∘ₗ projL c) = dephasedDensity b ψ
  rw [Finset.sum_image (fun i _ j _ h => line_injective b (Finset.mem_univ i) (Finset.mem_univ j) h)]
  apply LinearMap.ext
  intro x
  rw [LinearMap.sum_apply]
  show (∑ i, projL (ℂ ∙ (b i : H n)) (projL (ℂ ∙ ψ) (projL (ℂ ∙ (b i : H n)) x)))
    = dephasedDensity b ψ x
  rw [dephasedDensity_apply]
  apply Finset.sum_congr rfl
  intro i _
  show projL (ℂ ∙ (b i : H n)) (projL (ℂ ∙ ψ) (projL (ℂ ∙ (b i : H n)) x))
    = (basisWeight b ψ i : ℂ) • (⟪b i, x⟫_ℂ • b i)
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit (b i) x (b.norm_eq_one i)]
  rw [map_smul]
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit ψ (b i) hψ]
  rw [map_smul]
  rw [map_smul]
  rw [QuantumFoundations.Uhlhorn.projL_singleton_unit (b i) ψ (b.norm_eq_one i)]
  rw [smul_smul, smul_smul, smul_smul]
  congr 1
  show ⟪b i, x⟫_ℂ * ⟪ψ, b i⟫_ℂ * ⟪(b i : H n), ψ⟫_ℂ = (basisWeight b ψ i : ℂ) * ⟪b i, x⟫_ℂ
  have hconj : ⟪ψ, b i⟫_ℂ = (starRingEnd ℂ) ⟪(b i : H n), ψ⟫_ℂ := (inner_conj_symm _ _).symm
  have hw : (basisWeight b ψ i : ℂ) = ⟪(b i : H n), ψ⟫_ℂ * (starRingEnd ℂ) ⟪(b i : H n), ψ⟫_ℂ := by
    show ((‖⟪(b i : H n), ψ⟫_ℂ‖ ^ 2 : ℝ) : ℂ) = _
    rw [Complex.mul_conj']
    push_cast
    ring
  rw [hconj, hw]
  ring

end QuantumFoundations.Selector
