import QuantumFoundations.Complexity.Models.MeasurementGeneration.NoisyGeneration
import QuantumFoundations.Complexity.Models.NoisyRepetition.Persistence

/-!
# C11i — Unitary generation meets the branch-complexity gap

The two states unitarily generated by `noisyMeasurementCircuit p R` from the
blank-record inputs `basis00 R`/`basis10 R` are, by
`noisyMeasurement_maps_basis00`/`noisyMeasurement_maps_basis10`, *exactly*
`noisyZeroBranch p R`/`noisyOneBranch p R` — the very states C10's
`noisy_repetition_has_proxy_gap` and `noisy_repetition_gap_persists_under_circuit`
already certify. This file records that identification explicitly: the
dynamically generated branches carry the same robust proxy gap and the same
conditional persistence under further circuit evolution, with no new
distinguishability argument required.
-/

namespace QuantumFoundations.Complexity.MeasurementGeneration

open Gleason
open QuantumFoundations.BranchesRiedel
open QuantumFoundations.Complexity
open QuantumFoundations.Complexity.RepetitionModel
open QuantumFoundations.Complexity.NoisyRepetitionModel

noncomputable section

/-! ## C11i.1 — Unitarily generated branches carry the robust proxy gap -/

/-- The two branches dynamically generated from blank records by
`noisyMeasurementCircuit p R` satisfy the same robust subtraction-free proxy
gap as the static `noisyZeroBranch`/`noisyOneBranch` pair: generation and
persistence are the same states, not merely analogous ones. -/
theorem unitary_generation_produces_robust_branches
    (p : NoiseProfile) (hp : p.IsRobust) (R : ℕ) [NeZero R]
    (g : ℕ) (hg : 1 + g ≤ ceilHalf R) :
    HasProxyGapAtLeast (sitesEquivR (R + 1))
      (Circuit.evalOnH (noisyMeasurementCircuit p R) (sitesEquivR (R + 1)) (basis00 R))
      (Circuit.evalOnH (noisyMeasurementCircuit p R) (sitesEquivR (R + 1)) (basis10 R))
      (1 / 2 : ℝ) g := by
  rw [noisyMeasurement_maps_basis00, noisyMeasurement_maps_basis10]
  exact noisy_repetition_has_proxy_gap p hp R g hg

/-! ## C11i.2 — Conditional persistence of the generated branches -/

/-- The proxy gap of the dynamically generated branches persists through any
further finite `2`-local circuit evolution `E`, as long as the record budget
also covers four times `E`'s length. This is
`noisy_repetition_gap_persists_under_circuit` transported along the
generation identification: the generated branches are exactly
`noisyZeroBranch`/`noisyOneBranch`, so their post-generation robustness is
inherited, not separately re-derived. -/
theorem generated_branches_persist_under_further_evolution
    (p : NoiseProfile) (hp : p.IsRobust) (R : ℕ) [NeZero R]
    (E : Circuit (R + 1) 2) (g : ℕ) (hbudget : 1 + 4 * E.length + g ≤ ceilHalf R) :
    HasProxyGapAtLeast (sitesEquivR (R + 1))
      (Circuit.evalOnH E (sitesEquivR (R + 1))
        (Circuit.evalOnH (noisyMeasurementCircuit p R) (sitesEquivR (R + 1)) (basis00 R)))
      (Circuit.evalOnH E (sitesEquivR (R + 1))
        (Circuit.evalOnH (noisyMeasurementCircuit p R) (sitesEquivR (R + 1)) (basis10 R)))
      (1 / 2 : ℝ) g := by
  rw [noisyMeasurement_maps_basis00, noisyMeasurement_maps_basis10]
  exact noisy_repetition_gap_persists_under_circuit p hp R E g hbudget

#print axioms unitary_generation_produces_robust_branches
#print axioms generated_branches_persist_under_further_evolution

end

end QuantumFoundations.Complexity.MeasurementGeneration
