import QuantumFoundations.Complexity.ApproxBranchGap
import QuantumFoundations.Complexity.PersistenceMinima

/-!
# C8f — Conditional persistence of robust proxy gaps

The evolution remains an exact finite reversible circuit.  We transport the
complexity certificate produced by the initial approximate records; we do not
claim that the evolved vectors retain the same physical record projectors.
-/

namespace QuantumFoundations.Complexity

open Gleason
open QuantumFoundations.BranchesRiedel

noncomputable section

/-- The robust proxy gap generated by initial approximate records persists
through an exact reversible evolution when the record budget also pays twice
the conjugation overhead.  No additional analytic error is introduced. -/
theorem approximate_records_gap_persists_under_reversible_evolution
    {N d K R : ℕ} [NeZero R]
    (e : H (d ^ N) ≃ₗᵢ[ℂ] Sites N d)
    (regions : Fin R → Finset (Fin N))
    (recs : Fin R → LabeledResolution (d ^ N) K)
    (a b : H (d ^ N)) (r₀ : Fin R) (i j : Fin K)
    (ηi ηj ξ δ : ℝ)
    (ha : ‖a‖ = 1) (hb : ‖b‖ = 1)
    (happrox : ApproxRecordedPairOn recs a b i j ηi ηj)
    (hlocal_i : ∀ r, IsLocalTo
      (transportedRecordProj e (recs r) i) (regions r))
    (hlocal_j : ∀ r, IsLocalTo
      (transportedRecordProj e (recs r) j) (regions r))
    (hpairwise : ∀ r r', r ≠ r' → Disjoint (regions r) (regions r'))
    (hInterferenceThreshold : ηi + ηj < 2 * δ)
    (D : Circuit N d)
    (hRead : ApproximatesRecordPhaseFlipOn e D (recs r₀) j a b ξ)
    (hDistinguishabilityThreshold : 2 * δ + 2 * ηj + ξ ≤ 2)
    (Evo : ReversibleCircuitEvolution N d) (g : ℕ)
    (hbudget : Circuit.length D + 2 * Evo.overhead + g ≤ ceilHalf R) :
    HasProxyGapAtLeast e
      (Circuit.evalOnH Evo.forward e a)
      (Circuit.evalOnH Evo.forward e b) δ g := by
  have hInitial : HasProxyGapAtLeast e a b δ (g + 2 * Evo.overhead) :=
    approximate_records_give_proxy_gap_certificate
      e regions recs a b r₀ i j ηi ηj ξ δ ha hb happrox hlocal_i hlocal_j
      hpairwise hInterferenceThreshold D hRead hDistinguishabilityThreshold
      (g + 2 * Evo.overhead) (by omega)
  exact proxy_gap_persists_under_reversible_evolution Evo e a b δ g hInitial

/-- For canonical circuit evolution, the reversible overhead is twice the
evolution length, so the robust gap budget loses four evolution gates. -/
theorem approximate_records_gap_persists_under_circuit_evolution
    {N d K R : ℕ} [NeZero R]
    (e : H (d ^ N) ≃ₗᵢ[ℂ] Sites N d)
    (regions : Fin R → Finset (Fin N))
    (recs : Fin R → LabeledResolution (d ^ N) K)
    (a b : H (d ^ N)) (r₀ : Fin R) (i j : Fin K)
    (ηi ηj ξ δ : ℝ)
    (ha : ‖a‖ = 1) (hb : ‖b‖ = 1)
    (happrox : ApproxRecordedPairOn recs a b i j ηi ηj)
    (hlocal_i : ∀ r, IsLocalTo
      (transportedRecordProj e (recs r) i) (regions r))
    (hlocal_j : ∀ r, IsLocalTo
      (transportedRecordProj e (recs r) j) (regions r))
    (hpairwise : ∀ r r', r ≠ r' → Disjoint (regions r) (regions r'))
    (hInterferenceThreshold : ηi + ηj < 2 * δ)
    (D : Circuit N d)
    (hRead : ApproximatesRecordPhaseFlipOn e D (recs r₀) j a b ξ)
    (hDistinguishabilityThreshold : 2 * δ + 2 * ηj + ξ ≤ 2)
    (E : Circuit N d) (g : ℕ)
    (hbudget : Circuit.length D + 4 * Circuit.length E + g ≤ ceilHalf R) :
    HasProxyGapAtLeast e
      (Circuit.evalOnH E e a) (Circuit.evalOnH E e b) δ g := by
  let Evo := ReversibleCircuitEvolution.ofCircuit E
  have hbudget' : Circuit.length D + 2 * Evo.overhead + g ≤ ceilHalf R := by
    rw [show Evo.overhead = 2 * Circuit.length E from
      ReversibleCircuitEvolution.overhead_ofCircuit E]
    omega
  exact approximate_records_gap_persists_under_reversible_evolution
    e regions recs a b r₀ i j ηi ηj ξ δ ha hb happrox hlocal_i hlocal_j
    hpairwise hInterferenceThreshold D hRead hDistinguishabilityThreshold
    Evo g hbudget'

/-- Minimum-level form of robust proxy-gap persistence.  The exact proxy
transport adds no error term; only the finite conjugation overhead is paid. -/
theorem approximate_records_complexity_gap_persists_under_reversible_evolution
    {N d K R : ℕ} [NeZero R]
    (e : H (d ^ N) ≃ₗᵢ[ℂ] Sites N d)
    (regions : Fin R → Finset (Fin N))
    (recs : Fin R → LabeledResolution (d ^ N) K)
    (a b : H (d ^ N)) (r₀ : Fin R) (i j : Fin K)
    (ηi ηj ξ δ : ℝ)
    (ha : ‖a‖ = 1) (hb : ‖b‖ = 1)
    (happrox : ApproxRecordedPairOn recs a b i j ηi ηj)
    (hlocal_i : ∀ r, IsLocalTo
      (transportedRecordProj e (recs r) i) (regions r))
    (hlocal_j : ∀ r, IsLocalTo
      (transportedRecordProj e (recs r) j) (regions r))
    (hpairwise : ∀ r r', r ≠ r' → Disjoint (regions r) (regions r'))
    (hInterferenceThreshold : ηi + ηj < 2 * δ)
    (D : Circuit N d)
    (hRead : ApproximatesRecordPhaseFlipOn e D (recs r₀) j a b ξ)
    (hDistinguishabilityThreshold : 2 * δ + 2 * ηj + ξ ≤ 2)
    (Evo : ReversibleCircuitEvolution N d) (g : ℕ)
    (hbudget : Circuit.length D + 2 * Evo.overhead + g ≤ ceilHalf R) :
    distinguishabilityComplexity e
        (Circuit.evalOnH Evo.forward e a)
        (Circuit.evalOnH Evo.forward e b) δ + (g : WithTop ℕ)
      ≤ interferenceComplexity e
        (Circuit.evalOnH Evo.forward e a)
        (Circuit.evalOnH Evo.forward e b) δ := by
  have hI := approximate_records_give_interference_lower_bound
    e regions recs a b i j ηi ηj δ ha hb happrox hlocal_i hlocal_j
    hpairwise hInterferenceThreshold
  have hD := approx_record_phase_flip_gives_upper_bound
    e D (recs r₀) j a b ηj ξ δ ha hb (happrox r₀).2 hRead
    hDistinguishabilityThreshold
  exact proxy_complexity_gap_persists_of_explicit_bounds Evo e a b δ
    (ceilHalf R) (Circuit.length D) hI hD g hbudget

#print axioms approximate_records_gap_persists_under_reversible_evolution
#print axioms approximate_records_gap_persists_under_circuit_evolution
#print axioms approximate_records_complexity_gap_persists_under_reversible_evolution

end

end QuantumFoundations.Complexity
