import QuantumFoundations.Selectors.BridgeMain

open QuantumFoundations
open QuantumFoundations.FiniteTensor
open QuantumFoundations.Selector

#check TensorDecomposition
#check canonicalTensorDecomposition
#check productStateCoordinates
#check tensorOperator
#check partialTraceAncilla
#check AncillaNeutralUnder
#check TensorMultiplicativeUnder
#check isotropicDensity
#check isotropicResidual
#check ancilla_self_value_eq_forces_t_eq_one
#check covariance_without_nsnc1

#print axioms QuantumFoundations.FiniteTensor.partialTraceAncilla_id
#print axioms QuantumFoundations.Selector.ancilla_self_value_eq_forces_t_eq_one
